/* ==========================================================================
   English Reboot — Этап 4: данные импровизации
   Файл: improv_us.js — 40 карточек ситуаций для импров-рулетки и 15 историй
   «Yes, and…». Написаны вручную. Карточка:
     { id, place, situation (по-русски), who, say (реплика собеседника),
       phrases: фразы-условия из content_us.js («вверни …»),
       samples: 3 образца носителя — каждая фраза-условие звучит хотя бы в одном }
   История «Yes, and…»: { id, title, ru, turns: [{ say, samples: [2] }] } — 3 хода.
   Ситуации описаны без рода («Дверь захлопнулась»), чтобы подходить всем.
   ========================================================================== */

const IMPROV_CARDS = [
  { id: 'cafe-wrong-order', place: 'Кофейня', situation: 'Тебе принесли чай, а заказ был — латте.', who: 'Barista', say: "Here's your hot tea! Enjoy!",
    phrases: ["Excuse me, this isn't what I ordered", 'No problem'],
    samples: ["Excuse me, this isn't what I ordered — I asked for a latte.", 'Oh, no problem, but can I get the latte I ordered?', "Excuse me, this isn't what I ordered. Could you fix it?"] },
  { id: 'cafe-split', place: 'Ресторан', situation: 'Ужин с друзьями закончился, официант принёс один счёт на всех.', who: 'Waiter', say: "Here's the check! No rush.",
    phrases: ['Can we split the check?', 'Separate checks, please', 'My treat'],
    samples: ['Thanks! Can we split the check three ways?', "Oh, separate checks, please, if that's okay.", "Actually, it's my treat tonight — I've got it."] },
  { id: 'cafe-order', place: 'Ресторан', situation: 'Официант подошёл, а меню ещё не прочитано.', who: 'Waiter', say: 'Are you ready to order, or do you need a minute?',
    phrases: ['What do you recommend?', "We're still deciding", "I'll have the burger"],
    samples: ["We're still deciding. What do you recommend?", 'Hmm, what do you recommend here?', "I'll have the burger, please. Medium rare."] },
  { id: 'shop-size', place: 'Магазин одежды', situation: 'Понравилась куртка, но размер не тот.', who: 'Sales assistant', say: 'That jacket looks great! Want to try it on?',
    phrases: ['Do you have this in a medium?', 'Can I try this on?', "It's a little tight"],
    samples: ['Yes! Do you have this in a medium?', 'Sure, can I try this on in a medium?', "I tried it — it's a little tight. Do you have a bigger one?"] },
  { id: 'shop-price', place: 'Магазин', situation: 'Цена оказалась намного выше ожидаемой.', who: 'Cashier', say: "That'll be two hundred dollars.",
    phrases: ["That's out of my price range", 'Do you have anything cheaper?', "I'll think about it"],
    samples: ["Oh wow, that's out of my price range.", 'Hmm, do you have anything cheaper?', "Thanks, I'll think about it."] },
  { id: 'airport-delay', place: 'Аэропорт', situation: 'Рейс задержали, а друг уже ждёт в аэропорту прилёта.', who: 'Friend (phone)', say: "Hey! Where are you? I'm at the airport waiting!",
    phrases: ['My flight got delayed', 'Sorry to keep you waiting'],
    samples: ['Ugh, my flight got delayed. Sorry!', 'Sorry to keep you waiting — my flight got delayed two hours.', 'Bad news: my flight got delayed. Go grab a coffee!'] },
  { id: 'airport-luggage', place: 'Выдача багажа', situation: 'Все чемоданы уже забрали, а твоего нет.', who: 'Airline agent', say: 'Hi there, how can I help you?',
    phrases: ['My luggage is missing', 'I just landed'],
    samples: ['Hi, my luggage is missing.', 'I just landed from Chicago and my luggage is missing.', "Hi! I just landed, and my bag didn't come out."] },
  { id: 'hotel-ac', place: 'Отель', situation: 'В номере жарко: кондиционер не работает.', who: 'Front desk', say: 'Front desk, how can I help?',
    phrases: ["The AC isn't working", 'Could I switch rooms?'],
    samples: ["Hi, the AC isn't working in my room.", "Hi! The AC isn't working. Could I switch rooms?", "Could I switch rooms? It's really hot in here."] },
  { id: 'hotel-late', place: 'Отель', situation: 'Самолёт вечером, а выезд из номера в 11 утра.', who: 'Receptionist', say: 'Checkout is at eleven. Anything else?',
    phrases: ['Can I get a late checkout?', 'Can I leave my bags here?'],
    samples: ['Actually, can I get a late checkout?', 'Can I leave my bags here until five?', "My flight's at nine — can I get a late checkout?"] },
  { id: 'late-meeting', place: 'Дорога на встречу', situation: 'Встреча уже началась, а ты в пробке.', who: 'Coworker (phone)', say: 'Hey, the meeting started. Where are you?',
    phrases: ["I'm stuck in traffic", "I'll be there in five", "I'm on my way"],
    samples: ["So sorry, I'm stuck in traffic.", "I'm on my way! I'll be there in five.", "I'm stuck in traffic — start without me."] },
  { id: 'street-lost', place: 'Улица', situation: 'Музей где-то рядом, но найти его не получается.', who: 'Local', say: 'You look a little lost. Need help?',
    phrases: ["I'm lost", 'How do I get to downtown?', 'Can you show me on the map?'],
    samples: ["Yes, honestly, I'm lost.", 'Yeah, how do I get to downtown?', "That'd be great! Can you show me on the map?"] },
  { id: 'bus', place: 'Автобус', situation: 'Нужно доехать до музея, а маршрут незнакомый.', who: 'Bus driver', say: 'Morning! Where are you headed?',
    phrases: ['Does this bus go downtown?', 'Which stop do I get off at?'],
    samples: ['Hi! Does this bus go downtown?', "I'm going to the museum. Which stop do I get off at?", 'Does this bus go downtown? Which stop do I get off at?'] },
  { id: 'work-report', place: 'Офис', situation: 'Начальник спрашивает про отчёт, а он ещё не готов.', who: 'Boss', say: 'Hey, is the report ready?',
    phrases: ["I'm swamped", 'Let me get back to you on that', "I'll keep you posted"],
    samples: ["Sorry, I'm swamped this week.", 'Almost. Let me get back to you on that by Friday.', "Almost done. I'll keep you posted."] },
  { id: 'work-help', place: 'Офис', situation: 'Коллега просит помочь, а у тебя аврал.', who: 'Coworker', say: 'Do you have a minute? I need help with this file.',
    phrases: ["I'm swamped", 'Can we touch base tomorrow?', "I'll take care of it"],
    samples: ["Sorry, I'm swamped right now.", 'Can we touch base tomorrow morning?', "Sure, send it over — I'll take care of it."] },
  { id: 'call-mute', place: 'Созвон', situation: 'Ты говоришь, но тебя никто не слышит.', who: 'Coworker', say: "Hello? We can't hear you!",
    phrases: ['Sorry, I was on mute', 'Can you hear me?'],
    samples: ['Oh! Sorry, I was on mute.', 'Can you hear me now?', 'Sorry, I was on mute. Can you hear me?'] },
  { id: 'call-jump-in', place: 'Созвон', situation: 'Хочется вставить слово, пока менеджер говорит.', who: 'Manager', say: "...so that's the plan for next quarter.",
    phrases: ['Can I jump in here?', 'Sorry to interrupt', "That's a great point"],
    samples: ['Sorry to interrupt — can I jump in here?', "That's a great point. Can I add something?", 'Can I jump in here for a sec?'] },
  { id: 'call-reschedule', place: 'Созвон', situation: 'Встречу с клиентом нужно перенести.', who: 'Client', say: "So, are we still on for three o'clock?",
    phrases: ['Can we reschedule?', 'Something came up', "I can't make it"],
    samples: ['Actually, something came up. Can we reschedule?', "Sorry, I can't make it at three.", 'Can we reschedule for tomorrow?'] },
  { id: 'party-yes', place: 'Друзья', situation: 'Друг зовёт на вечеринку в субботу.', who: 'Friend', say: 'Party at my place Saturday! You in?',
    phrases: ["I'm in", 'Count me in', "I'll bring snacks"],
    samples: ["I'm in! What time?", 'Count me in!', "Sounds fun — I'll bring snacks."] },
  { id: 'concert-no', place: 'Друзья', situation: 'Друг зовёт на концерт, а сил совсем нет.', who: 'Friend', say: 'Wanna go to a concert tonight?',
    phrases: ['Rain check?', "I'm not feeling it tonight", 'Count me out'],
    samples: ["Ugh, I'm not feeling it tonight. Rain check?", "Rain check? I'm exhausted.", 'Count me out tonight, sorry!'] },
  { id: 'meet-where', place: 'Друзья', situation: 'Договариваетесь, где и когда встретиться.', who: 'Friend', say: 'So where should we meet?',
    phrases: ['What time works for you?', "Let's play it by ear", "I'll meet you there"],
    samples: ["Let's play it by ear. What time works for you?", "How about the park? I'll meet you there.", 'Downtown? What time works for you?'] },
  { id: 'good-news', place: 'Друзья', situation: 'Подругу повысили на работе.', who: 'Friend', say: 'Guess what? I got a promotion!',
    phrases: ['Congrats!', "I'm happy for you", "That's amazing!"],
    samples: ["Congrats! That's amazing!", "Wow! I'm happy for you!", "That's amazing! You deserve it."] },
  { id: 'bad-news', place: 'Друзья', situation: 'Друг расстроен: не взяли на работу мечты.', who: 'Friend', say: "I didn't get the job...",
    phrases: ["I'm sorry to hear that", 'That sucks', "You've got this"],
    samples: ["Oh, I'm sorry to hear that.", 'That sucks. Their loss!', "The next one is yours. You've got this."] },
  { id: 'neighbor-noise', place: 'Дом', situation: 'Сосед снизу жалуется на громкую музыку.', who: 'Neighbor', say: 'Hey, the music is really loud...',
    phrases: ['Sorry about the noise', "I didn't mean to"],
    samples: ["Oh, sorry about the noise! I'll turn it down.", "Sorry, I didn't mean to bother you.", "Sorry about the noise — I didn't mean to."] },
  { id: 'locked-out', place: 'Дом', situation: 'Дверь захлопнулась, ключи внутри. Звонишь соседке.', who: 'Maggie', say: "Hey! What's up?",
    phrases: ['I locked myself out', 'Do you have a spare key?'],
    samples: ['Hey, I locked myself out!', 'Do you have a spare key? I locked myself out.', 'Ugh, long story. Do you have a spare key?'] },
  { id: 'dishes', place: 'Дом', situation: 'Соседка намекает, что сегодня твоя очередь мыть посуду.', who: 'Roommate', say: "So... whose turn is it to do the dishes?",
    phrases: ["I'll clean up", 'Sorry, my mistake'],
    samples: ["Oh, sorry, my mistake — I'll clean up.", "Mine! I'll clean up after dinner.", 'Sorry, my mistake. Doing them now.'] },
  { id: 'doctor', place: 'У врача', situation: 'Со вчерашнего дня болит горло.', who: 'Doctor', say: 'So, what seems to be the problem?',
    phrases: ['I have a sore throat', "I don't feel well", "I think I'm coming down with something"],
    samples: ['I have a sore throat and a headache.', "I don't feel well since yesterday.", "I think I'm coming down with something."] },
  { id: 'sick-day', place: 'Работа', situation: 'Утром температура — звонишь начальнику.', who: 'Boss', say: 'Morning! Are you coming in today?',
    phrases: ["I'm calling in sick", "I'm feeling under the weather"],
    samples: ["I'm sorry, I'm calling in sick today.", "I'm feeling under the weather. Can I work from home?", "I'm calling in sick — I have a fever."] },
  { id: 'card-declined', place: 'Касса', situation: 'Карта не прошла, а очередь ждёт.', who: 'Cashier', say: 'Hmm, your card was declined.',
    phrases: ['Do you accept Apple Pay?', 'Can I pay by phone?'],
    samples: ["That's weird. Do you accept Apple Pay?", 'Can I pay by phone instead?', 'Hmm. Do you accept Apple Pay?'] },
  { id: 'friend-paid', place: 'Друзья', situation: 'Друг неожиданно заплатил за тебя в кафе.', who: 'Friend', say: 'Relax, I got this one.',
    phrases: ['I owe you one', "I'll pay you back", "I'll Venmo you"],
    samples: ['Thanks! I owe you one.', "Aw, thanks — I'll pay you back.", "You're the best. I'll Venmo you!"] },
  { id: 'date-invite', place: 'Свидание', situation: 'Человек, с которым вы давно переписываетесь, зовёт на свидание.', who: 'Match', say: 'So... would you like to go out sometime?',
    phrases: ["I'd love to", 'Are you free this weekend?', "It's a date"],
    samples: ["I'd love to! Are you free this weekend?", 'Sure! Are you free this weekend?', "Saturday at seven? It's a date."] },
  { id: 'game', place: 'Спорт', situation: 'Друг пропустил матч и спрашивает, как всё прошло.', who: 'Friend', say: 'Did you catch the game last night?',
    phrases: ['We crushed them', 'What a game!'],
    samples: ['Yeah! We crushed them!', 'What a game! Did you see the last shot?', 'Of course. We crushed them, five to one.'] },
  { id: 'spoilers', place: 'Досуг', situation: 'Коллега хочет пересказать финал сериала, который ты ещё смотришь.', who: 'Coworker', say: 'Oh my gosh, did you see the ending?!',
    phrases: ['No spoilers!', "I'm hooked"],
    samples: ["No spoilers! I'm on episode five.", 'Stop! No spoilers, please!', "I'm only on episode three, and I'm hooked."] },
  { id: 'exam', place: 'Учёба', situation: 'Одногруппник спрашивает, как прошёл экзамен.', who: 'Classmate', say: 'So how did the exam go?',
    phrases: ['I aced the exam', 'I bombed the test', 'I passed!'],
    samples: ['I aced the exam!', 'Honestly? I bombed the test.', 'I passed! Barely, but I passed!'] },
  { id: 'dont-get-it', place: 'Учёба', situation: 'Объяснение преподавателя прошло мимо.', who: 'Teacher', say: 'Any questions so far?',
    phrases: ["I don't get it", 'Can you explain that again?'],
    samples: ["Sorry, I don't get it.", 'Can you explain that again, please?', "I don't get it. Can you explain that again?"] },
  { id: 'phone-died', place: 'Телефон', situation: 'Телефон сел, а друг пять раз не смог дозвониться.', who: 'Friend', say: "Why didn't you answer? I called you five times!",
    phrases: ['My phone died', 'Sorry, I missed your call'],
    samples: ['Sorry, my phone died!', 'Sorry, I missed your call. My battery was dead.', "My phone died, sorry! What's up?"] },
  { id: 'wifi-down', place: 'Кафе', situation: 'Интернет в кафе не работает, бариста спрашивает, всё ли в порядке.', who: 'Barista', say: 'Everything okay over there?',
    phrases: ['The Wi-Fi is down', "What's the Wi-Fi?"],
    samples: ['I think the Wi-Fi is down.', "Hmm, what's the Wi-Fi? It's not connecting.", 'The Wi-Fi is down, I think.'] },
  { id: 'movie-opinion', place: 'Мнения', situation: 'Друг в восторге от фильма, а тебе он не понравился.', who: 'Friend', say: 'That movie was the best thing ever, right?',
    phrases: ['Honestly', "I see where you're coming from", 'Agree to disagree'],
    samples: ['Honestly? It was a total letdown.', "I see where you're coming from, but it was too long.", "Let's agree to disagree!"] },
  { id: 'risky-plan', place: 'Работа', situation: 'Коллега предлагает рискованный план запуска.', who: 'Coworker', say: 'I think we should launch it next week!',
    phrases: ["I'm on the fence", 'If you ask me', "Don't get me wrong"],
    samples: ["I'm on the fence about it.", 'If you ask me, we need another week.', "Don't get me wrong, I love it — but it's risky."] },
  { id: 'busy-call', place: 'Телефон', situation: 'Звонит друг, а ты на совещании.', who: 'Friend', say: 'Hey! Got a sec?',
    phrases: ["I'm in a meeting", 'Can I call you back?', "I'll call you back"],
    samples: ["Sorry, I'm in a meeting. Can I call you back?", 'Can I call you back in ten?', "I'm in a meeting — I'll call you back!"] },
  { id: 'weather', place: 'Small talk', situation: 'Сосед в лифте заводит разговор о погоде.', who: 'Neighbor', say: 'Crazy weather, huh?',
    phrases: ["It's freezing out there", "It's a nice day out"],
    samples: ["I know! It's freezing out there.", "Yeah, but they say it's a nice day out tomorrow.", "Seriously, it's freezing out there!"] },
];

const YES_AND_STORIES = [
  { id: 'snake', title: 'Сосед со змеёй', ru: 'Соседка делится странной новостью про нового соседа.', turns: [
    { say: 'So, I just met our new neighbor... he has a pet snake.', samples: ['No way! A real snake? How big is it?', 'Yikes! Does it live in his apartment?'] },
    { say: 'Yeah, and he asked me to watch it this weekend.', samples: ["And you said yes? You're braver than me!", 'Wait, what did you say?'] },
    { say: 'I said yes. So... want to help me?', samples: ['Ha! Count me out!', "Okay, but I'm not touching it!"] },
  ] },
  { id: 'lost-phone', title: 'Потерянный телефон', ru: 'Друг потерял телефон в такси.', turns: [
    { say: 'I left my phone in a cab last night.', samples: ['Oh no! Did you call the cab company?', 'Seriously? How are you texting me then?'] },
    { say: 'The driver called me this morning. He found it!', samples: ["That's amazing! What a nice guy.", 'Wow, lucky you! Did you give him a tip?'] },
    { say: "He wants to bring it over... but he's in New Jersey.", samples: ["Ha! Maybe you should meet halfway.", "That's a long drive. Buy him lunch!"] },
  ] },
  { id: 'boss-surprise', title: 'Сюрприз для начальника', ru: 'Коллега придумал сюрприз на день рождения начальника.', turns: [
    { say: "Let's throw a surprise party for the boss tomorrow!", samples: ["I'm in! What should we bring?", 'Love it! Does anyone know what cake she likes?'] },
    { say: 'Great. You can keep her busy for an hour.', samples: ["Me? Okay, I'll ask her about the budget. That takes forever.", 'Ha, okay. I\'ll schedule a "quick" meeting.'] },
    { say: "Uh-oh... she's walking this way right now!", samples: ['Act natural! Talk about the weather!', "Quick, hide the balloons!"] },
  ] },
  { id: 'pizza', title: 'Пицца в три ночи', ru: 'Соседка не может уснуть и хочет есть.', turns: [
    { say: "I can't sleep. I'm starving.", samples: ["Same. Let's order a pizza.", 'Me too! Is anything still open?'] },
    { say: 'The only place open has pineapple pizza.', samples: ["Honestly? I'm okay with that.", 'Ugh, fine. Hunger wins.'] },
    { say: "They say it'll take two hours.", samples: ["Two hours? Let's just make toast.", "Okay, plan B: cereal."] },
  ] },
  { id: 'wrong-text', title: 'Не тому человеку', ru: 'Коллега отправил сообщение не в тот чат.', turns: [
    { say: 'I just sent a text about my boss... to my boss.', samples: ['Oh no! What did it say?', 'Yikes. Can you delete it?'] },
    { say: 'It said: "She is so slow on Mondays."', samples: ['Hmm. Maybe say it was a joke?', "Well... at least it's true?"] },
    { say: 'She just replied: "Tuesdays too."', samples: ['Ha! She has a sense of humor!', 'Okay, that was actually funny.'] },
  ] },
  { id: 'celebrity', title: 'Встреча со звездой', ru: 'Друг увидел знаменитость в метро.', turns: [
    { say: 'I just saw a famous actor on the subway!', samples: ['No way! Did you talk to him?', 'Seriously? Who was it?'] },
    { say: 'I asked for a photo, and he said yes!', samples: ['That\'s amazing! Send it to me!', 'Lucky you! Was he nice?'] },
    { say: 'But my phone died right before the photo.', samples: ['Oh no! That\'s so sad.', 'Ha! Classic. So no proof?'] },
  ] },
  { id: 'vacation', title: 'Отпуск мечты', ru: 'Друг планирует отпуск.', turns: [
    { say: "I'm taking two weeks off next month!", samples: ['Nice! Where are you going?', 'Lucky you! Any plans?'] },
    { say: "I'm thinking about Iceland. Hot springs, northern lights...", samples: ["That sounds amazing! Isn't it super cold?", "Wow! Can I come with you?"] },
    { say: 'The only problem: I hate the cold.', samples: ['Ha! Then maybe Hawaii?', "Pack a lot of sweaters, I guess!"] },
  ] },
  { id: 'office-cat', title: 'Кот на работе', ru: 'В офис кто-то принёс кота.', turns: [
    { say: "There's a cat in the office today.", samples: ['What? Whose cat is it?', 'No way! Is it friendly?'] },
    { say: "It's sleeping on the manager's keyboard.", samples: ["Ha! Best employee ever.", "Somebody take a picture!"] },
    { say: 'And it just sent an email to the whole company.', samples: ["Ha! What did it say?", "That's the best email this year."] },
  ] },
  { id: 'bad-date', title: 'Неудачное свидание', ru: 'Подруга рассказывает о свидании.', turns: [
    { say: 'My date last night was a disaster.', samples: ['Oh no! What happened?', 'Really? Tell me everything!'] },
    { say: 'He talked about his ex for two hours.', samples: ['Two hours? Yikes!', "That's a red flag."] },
    { say: 'Then he asked me out again.', samples: ["Ha! And what did you say?", "Please tell me you said no."] },
  ] },
  { id: 'coffee-machine', title: 'Новая кофемашина', ru: 'В офисе поставили новую кофемашину.', turns: [
    { say: 'We got a new coffee machine in the kitchen!', samples: ['Finally! Is it any good?', 'Nice! Does it make lattes?'] },
    { say: 'It has fifty buttons and no instructions.', samples: ['Ha! Good luck with that.', "I'll just press them all."] },
    { say: 'Tony pressed one and now it only makes hot chocolate.', samples: ["Honestly, I'm not mad about that.", 'Classic Tony!'] },
  ] },
  { id: 'movie-fight', title: 'Спор о кино', ru: 'Друг выбирает фильм на вечер.', turns: [
    { say: "Let's watch a horror movie tonight!", samples: ['Hmm, maybe a comedy instead?', "Okay, but I'm sleeping with the lights on."] },
    { say: "Come on, it's not that scary.", samples: ["That's what you said last time.", "Fine, but you're making popcorn."] },
    { say: "Okay... I'm actually too scared to watch it alone.", samples: ['Ha! I knew it!', 'Fine, comedy it is.'] },
  ] },
  { id: 'marathon', title: 'Марафон', ru: 'Друг решил пробежать марафон.', turns: [
    { say: "I signed up for a marathon!", samples: ['Wow! When is it?', "That's awesome! How far can you run now?"] },
    { say: "It's in two weeks.", samples: ['Two weeks? Are you ready?', "Wow, that soon? You're crazy!"] },
    { say: "I've never run more than five miles.", samples: ['Uh-oh. Maybe walk part of it?', "Well, you've got this... I hope!"] },
  ] },
  { id: 'missed-bus', title: 'Уехавший автобус', ru: 'Друг опоздал на автобус.', turns: [
    { say: 'I missed the last bus home.', samples: ['Oh no! Where are you now?', "Seriously? Do you need a ride?"] },
    { say: "I'm at a diner. They're closing soon.", samples: ['Want me to pick you up?', "I'll grab an Uber for you."] },
    { say: 'The cook says I can help him close and he\'ll drive me.', samples: ["Ha! That's one way to get home.", 'Nice! Free food too?'] },
  ] },
  { id: 'gift', title: 'Подарок для мамы', ru: 'Друг не знает, что подарить маме.', turns: [
    { say: "My mom's birthday is tomorrow and I have nothing.", samples: ['Uh-oh. What does she like?', "Tomorrow? Let's go shopping now!"] },
    { say: 'She likes gardening and cooking.', samples: ['How about a cooking class?', 'Maybe some plants for her garden?'] },
    { say: 'Last year I got her a plant. It died in a week.', samples: ['Ha! Then a cooking class it is.', "Okay, no more plants."] },
  ] },
  { id: 'secret', title: 'Секрет соседки', ru: 'Мэгги вот-вот расскажет секрет.', turns: [
    { say: "Can you keep a secret?", samples: ['Of course! What is it?', 'Sure, my lips are sealed.'] },
    { say: "I'm moving to California... next month.", samples: ['What? No way! Why?', "Wow! I'm happy for you... but I'll miss you!"] },
    { say: "Just kidding! But you should see your face!", samples: ['Ha! You got me!', "Not funny! ...Okay, a little funny."] },
  ] },
];

if (typeof window !== 'undefined') { window.IMPROV_CARDS = IMPROV_CARDS; window.YES_AND_STORIES = YES_AND_STORIES; }
if (typeof globalThis !== 'undefined') { globalThis.IMPROV_CARDS = IMPROV_CARDS; globalThis.YES_AND_STORIES = YES_AND_STORIES; }
