/* ==========================================================================
   English Reboot — Этап 4: данные импровизации
   Файл: improv_us.js — 140 карточек ситуаций (50 — A1, 50 — A1+) для импров-рулетки и 15 историй
   «Yes, and…». Написаны вручную. Карточка:
     { id, place, situation (по-русски), who, say (реплика собеседника),
       phrases: фразы-условия из content_us.js («вверни …»),
       samples: 3 образца носителя — каждая фраза-условие звучит хотя бы в одном }
   История «Yes, and…»: { id, title, ru, turns: [{ say, samples: [2] }] } — 3 хода.
   Ситуации описаны без рода («Дверь захлопнулась»), чтобы подходить всем.
   ========================================================================== */

const IMPROV_CARDS = [
  { id: 'cafe-wrong-order', place: 'Кофейня', situation: 'Тебе принесли чай, а заказ был — латте.', who: 'Barista', say: "Here's your hot tea! Enjoy!",
    phrases: ["Excuse me, this isn't what I ordered", 'No problem'],
    samples: ["Excuse me, this isn't what I ordered — I asked for a latte.", 'Oh, no problem, but can I get the latte I ordered?', "Excuse me, this isn't what I ordered. Could you fix it?"] },
  { id: 'cafe-split', place: 'Ресторан', situation: 'Ужин с друзьями закончился, официант принёс один счёт на всех.', who: 'Waiter', say: "Here's the check! No rush.",
    phrases: ['Can we split the check?', 'Separate checks, please', 'My treat'],
    samples: ['Thanks! Can we split the check three ways?', "Oh, separate checks, please, if that's okay.", "Actually, it's my treat tonight — I've got it."] },
  { id: 'cafe-order', place: 'Ресторан', situation: 'Официант подошёл, а меню ещё не прочитано.', who: 'Waiter', say: 'Are you ready to order, or do you need a minute?',
    phrases: ['What do you recommend?', "We're still deciding", "I'll have the burger"],
    samples: ["We're still deciding. What do you recommend?", 'Hmm, what do you recommend here?', "I'll have the burger, please. Medium rare."] },
  { id: 'shop-size', place: 'Магазин одежды', situation: 'Понравилась куртка, но размер не тот.', who: 'Sales assistant', say: 'That jacket looks great! Want to try it on?',
    phrases: ['Do you have this in a medium?', 'Can I try this on?', "It's a little tight"],
    samples: ['Yes! Do you have this in a medium?', 'Sure, can I try this on in a medium?', "I tried it — it's a little tight. Do you have a bigger one?"] },
  { id: 'shop-price', place: 'Магазин', situation: 'Цена оказалась намного выше ожидаемой.', who: 'Cashier', say: "That'll be two hundred dollars.",
    phrases: ["That's out of my price range", 'Do you have anything cheaper?', "I'll think about it"],
    samples: ["Oh wow, that's out of my price range.", 'Hmm, do you have anything cheaper?', "Thanks, I'll think about it."] },
  { id: 'airport-delay', place: 'Аэропорт', situation: 'Рейс задержали, а друг уже ждёт в аэропорту прилёта.', who: 'Friend (phone)', say: "Hey! Where are you? I'm at the airport waiting!",
    phrases: ['My flight got delayed', 'Sorry to keep you waiting'],
    samples: ['Ugh, my flight got delayed. Sorry!', 'Sorry to keep you waiting — my flight got delayed two hours.', 'Bad news: my flight got delayed. Go grab a coffee!'] },
  { id: 'airport-luggage', place: 'Выдача багажа', situation: 'Все чемоданы уже забрали, а твоего нет.', who: 'Airline agent', say: 'Hi there, how can I help you?',
    phrases: ['My luggage is missing', 'I just landed'],
    samples: ['Hi, my luggage is missing.', 'I just landed from Chicago and my luggage is missing.', "Hi! I just landed, and my bag didn't come out."] },
  { id: 'hotel-ac', place: 'Отель', situation: 'В номере жарко: кондиционер не работает.', who: 'Front desk', say: 'Front desk, how can I help?',
    phrases: ["The AC isn't working", 'Could I switch rooms?'],
    samples: ["Hi, the AC isn't working in my room.", "Hi! The AC isn't working. Could I switch rooms?", "Could I switch rooms? It's really hot in here."] },
  { id: 'hotel-late', place: 'Отель', situation: 'Самолёт вечером, а выезд из номера в 11 утра.', who: 'Receptionist', say: 'Checkout is at eleven. Anything else?',
    phrases: ['Can I get a late checkout?', 'Can I leave my bags here?'],
    samples: ['Actually, can I get a late checkout?', 'Can I leave my bags here until five?', "My flight's at nine — can I get a late checkout?"] },
  { id: 'late-meeting', place: 'Дорога на встречу', situation: 'Встреча уже началась, а ты в пробке.', who: 'Coworker (phone)', say: 'Hey, the meeting started. Where are you?',
    phrases: ["I'm stuck in traffic", "I'll be there in five", "I'm on my way"],
    samples: ["So sorry, I'm stuck in traffic.", "I'm on my way! I'll be there in five.", "I'm stuck in traffic — start without me."] },
  { id: 'street-lost', place: 'Улица', situation: 'Музей где-то рядом, но найти его не получается.', who: 'Local', say: 'You look a little lost. Need help?',
    phrases: ["I'm lost", 'How do I get to downtown?', 'Can you show me on the map?'],
    samples: ["Yes, honestly, I'm lost.", 'Yeah, how do I get to downtown?', "That'd be great! Can you show me on the map?"] },
  { id: 'bus', place: 'Автобус', situation: 'Нужно доехать до музея, а маршрут незнакомый.', who: 'Bus driver', say: 'Morning! Where are you headed?',
    phrases: ['Does this bus go downtown?', 'Which stop do I get off at?'],
    samples: ['Hi! Does this bus go downtown?', "I'm going to the museum. Which stop do I get off at?", 'Does this bus go downtown? Which stop do I get off at?'] },
  { id: 'work-report', place: 'Офис', situation: 'Начальник спрашивает про отчёт, а он ещё не готов.', who: 'Boss', say: 'Hey, is the report ready?',
    phrases: ["I'm swamped", 'Let me get back to you on that', "I'll keep you posted"],
    samples: ["Sorry, I'm swamped this week.", 'Almost. Let me get back to you on that by Friday.', "Almost done. I'll keep you posted."] },
  { id: 'work-help', place: 'Офис', situation: 'Коллега просит помочь, а у тебя аврал.', who: 'Coworker', say: 'Do you have a minute? I need help with this file.',
    phrases: ["I'm swamped", 'Can we touch base tomorrow?', "I'll take care of it"],
    samples: ["Sorry, I'm swamped right now.", 'Can we touch base tomorrow morning?', "Sure, send it over — I'll take care of it."] },
  { id: 'call-mute', place: 'Созвон', situation: 'Ты говоришь, но тебя никто не слышит.', who: 'Coworker', say: "Hello? We can't hear you!",
    phrases: ['Sorry, I was on mute', 'Can you hear me?'],
    samples: ['Oh! Sorry, I was on mute.', 'Can you hear me now?', 'Sorry, I was on mute. Can you hear me?'] },
  { id: 'call-jump-in', place: 'Созвон', situation: 'Хочется вставить слово, пока менеджер говорит.', who: 'Manager', say: "...so that's the plan for next quarter.",
    phrases: ['Can I jump in here?', 'Sorry to interrupt', "That's a great point"],
    samples: ['Sorry to interrupt — can I jump in here?', "That's a great point. Can I add something?", 'Can I jump in here for a sec?'] },
  { id: 'call-reschedule', place: 'Созвон', situation: 'Встречу с клиентом нужно перенести.', who: 'Client', say: "So, are we still on for three o'clock?",
    phrases: ['Can we reschedule?', 'Something came up', "I can't make it"],
    samples: ['Actually, something came up. Can we reschedule?', "Sorry, I can't make it at three.", 'Can we reschedule for tomorrow?'] },
  { id: 'party-yes', place: 'Друзья', situation: 'Друг зовёт на вечеринку в субботу.', who: 'Friend', say: 'Party at my place Saturday! You in?',
    phrases: ["I'm in", 'Count me in', "I'll bring snacks"],
    samples: ["I'm in! What time?", 'Count me in!', "Sounds fun — I'll bring snacks."] },
  { id: 'concert-no', place: 'Друзья', situation: 'Друг зовёт на концерт, а сил совсем нет.', who: 'Friend', say: 'Wanna go to a concert tonight?',
    phrases: ['Rain check?', "I'm not feeling it tonight", 'Count me out'],
    samples: ["Ugh, I'm not feeling it tonight. Rain check?", "Rain check? I'm exhausted.", 'Count me out tonight, sorry!'] },
  { id: 'meet-where', place: 'Друзья', situation: 'Договариваетесь, где и когда встретиться.', who: 'Friend', say: 'So where should we meet?',
    phrases: ['What time works for you?', "Let's play it by ear", "I'll meet you there"],
    samples: ["Let's play it by ear. What time works for you?", "How about the park? I'll meet you there.", 'Downtown? What time works for you?'] },
  { id: 'good-news', place: 'Друзья', situation: 'Подругу повысили на работе.', who: 'Friend', say: 'Guess what? I got a promotion!',
    phrases: ['Congrats!', "I'm happy for you", "That's amazing!"],
    samples: ["Congrats! That's amazing!", "Wow! I'm happy for you!", "That's amazing! You deserve it."] },
  { id: 'bad-news', place: 'Друзья', situation: 'Друг расстроен: не взяли на работу мечты.', who: 'Friend', say: "I didn't get the job...",
    phrases: ["I'm sorry to hear that", 'That sucks', "You've got this"],
    samples: ["Oh, I'm sorry to hear that.", 'That sucks. Their loss!', "The next one is yours. You've got this."] },
  { id: 'neighbor-noise', place: 'Дом', situation: 'Сосед снизу жалуется на громкую музыку.', who: 'Neighbor', say: 'Hey, the music is really loud...',
    phrases: ['Sorry about the noise', "I didn't mean to"],
    samples: ["Oh, sorry about the noise! I'll turn it down.", "Sorry, I didn't mean to bother you.", "Sorry about the noise — I didn't mean to."] },
  { id: 'locked-out', place: 'Дом', situation: 'Дверь захлопнулась, ключи внутри. Звонишь соседке.', who: 'Maggie', say: "Hey! What's up?",
    phrases: ['I locked myself out', 'Do you have a spare key?'],
    samples: ['Hey, I locked myself out!', 'Do you have a spare key? I locked myself out.', 'Ugh, long story. Do you have a spare key?'] },
  { id: 'dishes', place: 'Дом', situation: 'Соседка намекает, что сегодня твоя очередь мыть посуду.', who: 'Roommate', say: "So... whose turn is it to do the dishes?",
    phrases: ["I'll clean up", 'Sorry, my mistake'],
    samples: ["Oh, sorry, my mistake — I'll clean up.", "Mine! I'll clean up after dinner.", 'Sorry, my mistake. Doing them now.'] },
  { id: 'doctor', place: 'У врача', situation: 'Со вчерашнего дня болит горло.', who: 'Doctor', say: 'So, what seems to be the problem?',
    phrases: ['I have a sore throat', "I don't feel well", "I think I'm coming down with something"],
    samples: ['I have a sore throat and a headache.', "I don't feel well since yesterday.", "I think I'm coming down with something."] },
  { id: 'sick-day', place: 'Работа', situation: 'Утром температура — звонишь начальнику.', who: 'Boss', say: 'Morning! Are you coming in today?',
    phrases: ["I'm calling in sick", "I'm feeling under the weather"],
    samples: ["I'm sorry, I'm calling in sick today.", "I'm feeling under the weather. Can I work from home?", "I'm calling in sick — I have a fever."] },
  { id: 'card-declined', place: 'Касса', situation: 'Карта не прошла, а очередь ждёт.', who: 'Cashier', say: 'Hmm, your card was declined.',
    phrases: ['Do you accept Apple Pay?', 'Can I pay by phone?'],
    samples: ["That's weird. Do you accept Apple Pay?", 'Can I pay by phone instead?', 'Hmm. Do you accept Apple Pay?'] },
  { id: 'friend-paid', place: 'Друзья', situation: 'Друг неожиданно заплатил за тебя в кафе.', who: 'Friend', say: 'Relax, I got this one.',
    phrases: ['I owe you one', "I'll pay you back", "I'll Venmo you"],
    samples: ['Thanks! I owe you one.', "Aw, thanks — I'll pay you back.", "You're the best. I'll Venmo you!"] },
  { id: 'date-invite', place: 'Свидание', situation: 'Человек, с которым вы давно переписываетесь, зовёт на свидание.', who: 'Match', say: 'So... would you like to go out sometime?',
    phrases: ["I'd love to", 'Are you free this weekend?', "It's a date"],
    samples: ["I'd love to! Are you free this weekend?", 'Sure! Are you free this weekend?', "Saturday at seven? It's a date."] },
  { id: 'game', place: 'Спорт', situation: 'Друг пропустил матч и спрашивает, как всё прошло.', who: 'Friend', say: 'Did you catch the game last night?',
    phrases: ['We crushed them', 'What a game!'],
    samples: ['Yeah! We crushed them!', 'What a game! Did you see the last shot?', 'Of course. We crushed them, five to one.'] },
  { id: 'spoilers', place: 'Досуг', situation: 'Коллега хочет пересказать финал сериала, который ты ещё смотришь.', who: 'Coworker', say: 'Oh my gosh, did you see the ending?!',
    phrases: ['No spoilers!', "I'm hooked"],
    samples: ["No spoilers! I'm on episode five.", 'Stop! No spoilers, please!', "I'm only on episode three, and I'm hooked."] },
  { id: 'exam', place: 'Учёба', situation: 'Одногруппник спрашивает, как прошёл экзамен.', who: 'Classmate', say: 'So how did the exam go?',
    phrases: ['I aced the exam', 'I bombed the test', 'I passed!'],
    samples: ['I aced the exam!', 'Honestly? I bombed the test.', 'I passed! Barely, but I passed!'] },
  { id: 'dont-get-it', place: 'Учёба', situation: 'Объяснение преподавателя прошло мимо.', who: 'Teacher', say: 'Any questions so far?',
    phrases: ["I don't get it", 'Can you explain that again?'],
    samples: ["Sorry, I don't get it.", 'Can you explain that again, please?', "I don't get it. Can you explain that again?"] },
  { id: 'phone-died', place: 'Телефон', situation: 'Телефон сел, а друг пять раз не смог дозвониться.', who: 'Friend', say: "Why didn't you answer? I called you five times!",
    phrases: ['My phone died', 'Sorry, I missed your call'],
    samples: ['Sorry, my phone died!', 'Sorry, I missed your call. My battery was dead.', "My phone died, sorry! What's up?"] },
  { id: 'wifi-down', place: 'Кафе', situation: 'Интернет в кафе не работает, бариста спрашивает, всё ли в порядке.', who: 'Barista', say: 'Everything okay over there?',
    phrases: ['The Wi-Fi is down', "What's the Wi-Fi?"],
    samples: ['I think the Wi-Fi is down.', "Hmm, what's the Wi-Fi? It's not connecting.", 'The Wi-Fi is down, I think.'] },
  { id: 'movie-opinion', place: 'Мнения', situation: 'Друг в восторге от фильма, а тебе он не понравился.', who: 'Friend', say: 'That movie was the best thing ever, right?',
    phrases: ['Honestly', "I see where you're coming from", 'Agree to disagree'],
    samples: ['Honestly? It was a total letdown.', "I see where you're coming from, but it was too long.", "Let's agree to disagree!"] },
  { id: 'risky-plan', place: 'Работа', situation: 'Коллега предлагает рискованный план запуска.', who: 'Coworker', say: 'I think we should launch it next week!',
    phrases: ["I'm on the fence", 'If you ask me', "Don't get me wrong"],
    samples: ["I'm on the fence about it.", 'If you ask me, we need another week.', "Don't get me wrong, I love it — but it's risky."] },
  { id: 'busy-call', place: 'Телефон', situation: 'Звонит друг, а ты на совещании.', who: 'Friend', say: 'Hey! Got a sec?',
    phrases: ["I'm in a meeting", 'Can I call you back?', "I'll call you back"],
    samples: ["Sorry, I'm in a meeting. Can I call you back?", 'Can I call you back in ten?', "I'm in a meeting — I'll call you back!"] },
  { id: 'weather', place: 'Small talk', situation: 'Сосед в лифте заводит разговор о погоде.', who: 'Neighbor', say: 'Crazy weather, huh?',
    phrases: ["It's freezing out there", "It's a nice day out"],
    samples: ["I know! It's freezing out there.", "Yeah, but they say it's a nice day out tomorrow.", "Seriously, it's freezing out there!"] },
  /* ---------- Пакет A1, часть 1: «Первая неделя в Нью-Йорке» (level — для будущего фильтра по уровню) ---------- */
  { id: 'a1-first-coffee', level: 'A1', place: 'Кофейня', situation: 'Первое утро в Нью-Йорке. Очередь длинная, бариста кричит «Next!».', who: 'Barista', say: 'Next! What can I get you?',
    phrases: ['A large, please', 'With milk', 'To go, please'],
    samples: ['Hi! Coffee. A large, please.', 'A large, please. With milk.', 'Coffee with milk. To go, please!'] },
  { id: 'a1-spicy', level: 'A1', place: 'Фудтрак', situation: 'Фудтрак с тако. В меню рядом с каждым блюдом нарисованы три перчика.', who: 'Food truck guy', say: 'Tacos! Chicken or beef?',
    phrases: ['Is it spicy?', "I don't eat meat"],
    samples: ['Chicken, please. Is it spicy?', "Sorry, I don't eat meat. Beans, please!", "I don't eat meat. Beans? Is it spicy?"] },
  { id: 'a1-diner-full', level: 'A1', place: 'Кухня', situation: 'Мэгги печёт блинчики и несёт тебе третий. Места в желудке больше нет.', who: 'Maggie', say: 'More pancakes, hon?',
    phrases: ["I'm full", "It's so good!"],
    samples: ["No, thank you! I'm full.", "It's so good! But I'm full.", "Oh no, I'm full. It's so good, though!"] },
  { id: 'a1-check', level: 'A1', place: 'Дайнер', situation: 'Ужин закончился, официант пропал. И вот он наконец идёт мимо.', who: 'Waiter', say: 'Everything okay over here?',
    phrases: ['Check, please', 'Can I pay by card?'],
    samples: ['Yes, thanks! Check, please.', "Everything's great. Can I pay by card?", 'Check, please! Can I pay by card?'] },
  { id: 'a1-restroom', level: 'A1', place: 'Кафе', situation: 'Срочно нужен туалет, а табличек нигде нет. Кассир улыбается и ждёт заказа.', who: 'Cashier', say: 'Hi! Ready to order?',
    phrases: ["Where's the restroom?", 'Is there a bathroom here?'],
    samples: ["Sorry, one sec — where's the restroom?", 'One minute! Is there a bathroom here?', "In a minute! Where's the restroom, please?"] },
  { id: 'a1-ice', level: 'A1', place: 'Кафе', situation: 'На улице мороз, а в газировку тебе уже сыплют гору льда.', who: 'Server', say: 'One soda, lots of ice!',
    phrases: ['No ice, please', 'Just water, thanks'],
    samples: ['Oh, no ice, please!', 'Actually, just water, thanks.', 'No ice, please. Or... just water, thanks.'] },
  { id: 'a1-what-time', level: 'A1', place: 'Улица', situation: 'Телефон сел, а в пять — важная встреча. Прохожий заметил панику на лице.', who: 'Stranger', say: 'You okay? You look worried.',
    phrases: ['What time is it?', 'My phone is dead'],
    samples: ['My phone is dead. What time is it?', 'Yes! What time is it, please?', 'My phone is dead! What time is it?'] },
  { id: 'a1-late', level: 'A1', place: 'Метро', situation: 'Тони ждёт у кинотеатра, фильм через пять минут, а поезд стоит в туннеле.', who: 'Tony (phone)', say: 'Hey, where are you? The movie starts at seven!',
    phrases: ["I'm late!", 'Five more minutes'],
    samples: ["Sorry, I'm late! Five more minutes!", "I'm on the subway. Five more minutes, okay?", "I'm late! I'm so sorry!"] },
  { id: 'a1-birthday', level: 'A1', place: 'Офис', situation: 'Прия заметила торт на твоём столе и шарик на стуле.', who: 'Priya', say: 'Wait, why is there a cake on your desk?',
    phrases: ["It's my birthday"],
    samples: ["It's my birthday!", "Surprise! It's my birthday today.", "Well... it's my birthday. Want some cake?"] },
  { id: 'a1-age', level: 'A1', place: 'Вечеринка', situation: 'Ребёнок соседей задаёт самые прямые вопросы на свете.', who: "Neighbor's kid", say: 'How old are you? You look old!',
    phrases: ["I'm twenty-five", 'How old are you?'],
    samples: ["Ha! I'm twenty-five. That's not old!", "I'm twenty-five. How old are you?", "Hey! I'm twenty-five!"] },
  { id: 'a1-market', level: 'A1', place: 'Фермерский рынок', situation: 'Фермер предлагает персики. Один персик — восемь долларов.', who: 'Farmer', say: 'Fresh peaches! Eight dollars each!',
    phrases: ["That's expensive", 'How many?'],
    samples: ["Eight? That's expensive!", "Wow, that's expensive. How many for ten?", "That's expensive! How many for five dollars?"] },
  { id: 'a1-no-time', level: 'A1', place: 'Улица', situation: 'Парень с планшетом просит подписать петицию, а поезд уходит через минуту.', who: 'Guy with a clipboard', say: 'Hi! Do you have a minute?',
    phrases: ["I don't have time", "I'm late!"],
    samples: ["Sorry, I don't have time!", "No, sorry, I'm late!", "I'm late! I don't have time, sorry!"] },
  { id: 'a1-five-more', level: 'A1', place: 'Дом', situation: 'Будильник звенел уже три раза. Сосед по квартире стучит в дверь.', who: 'Roommate', say: "Hey! It's eight! Get up!",
    phrases: ['Five more minutes'],
    samples: ['Five more minutes!', 'Ugh... five more minutes, please!', 'No... five more minutes. Please!'] },
  { id: 'a1-park', level: 'A1', place: 'Улица', situation: 'Нужно в Центральный парк, а стрелка на карте в телефоне крутится.', who: 'Officer', say: 'You need help?',
    phrases: ['How do I get there?', 'Is it near here?'],
    samples: ['Yes! Central Park. How do I get there?', 'Central Park — is it near here?', 'Is it near here? How do I get there?'] },
  { id: 'a1-right-bus', level: 'A1', place: 'Автобус', situation: 'Двери автобуса открылись, а номер на табло не разглядеть.', who: 'Bus driver', say: 'Getting on or not?',
    phrases: ['Is this the right bus?', 'Where do I get off?'],
    samples: ['Wait — is this the right bus? To Brooklyn?', 'Yes! Where do I get off for the park?', 'Is this the right bus to the zoo? Where do I get off?'] },
  { id: 'a1-directions', level: 'A1', place: 'Улица', situation: 'Прохожий объясняет дорогу и машет руками во все стороны сразу.', who: 'Local', say: 'The bank? Sure! Go two blocks, then...',
    phrases: ['Turn left', 'Turn right', 'Can you show me?'],
    samples: ['Turn left or turn right?', 'Sorry, can you show me?', 'So... turn left, then turn right?'] },
  { id: 'a1-taxi', level: 'A1', place: 'Улица', situation: 'Дождь. Вы с Джесс стоите на углу, до ресторана десять кварталов.', who: 'Jess', say: 'Ugh, rain! Walk or taxi?',
    phrases: ["Let's take a taxi", "Let's walk"],
    samples: ["Let's take a taxi!", "It's just rain. Let's walk!", "Let's walk... no, let's take a taxi!"] },
  { id: 'a1-seat', level: 'A1', place: 'Метро', situation: 'Вагон битком. Одно место свободно, но на нём чей-то пакет. Пассажир рядом поднимает глаза.', who: 'Passenger', say: 'Hm?',
    phrases: ['Is this seat free?'],
    samples: ['Hi! Is this seat free?', 'Excuse me, is this seat free?', 'Sorry — is this seat free?'] },
  { id: 'a1-new-here', level: 'A1', place: 'Подъезд', situation: 'Арендодатель мистер Окафор видит у подъезда незнакомца с чемоданами.', who: 'Mr. Okafor', say: "Good afternoon. I don't believe we have met.",
    phrases: ["I'm new here", 'I live with a roommate'],
    samples: ["Hi! I'm new here. I live on the third floor.", "I'm new here! I live with a roommate, Maggie.", "Hello! I'm new here."] },
  { id: 'a1-from', level: 'A1', place: 'Вечеринка', situation: 'Луис услышал твой акцент и очень хочет угадать страну.', who: 'Luis', say: 'Wait, let me guess... France?',
    phrases: ["I'm from Russia", 'This is my first time here'],
    samples: ["Ha! I'm from Russia.", "Good guess! But I'm from Russia. This is my first time here.", "Wrong! I'm from Russia. This is my first time here!"] },
  { id: 'a1-slowly', level: 'A1', place: 'Офис', situation: 'Прия, руководитель команды, объясняет задачу со скоростью пулемёта.', who: 'Priya', say: 'So-you-take-this-file-fix-it-send-it-to-Ray-by-noon-okay?',
    phrases: ['Slowly, please', "My English isn't great"],
    samples: ['Sorry, slowly, please!', "My English isn't great. Slowly, please?", "Sorry, my English isn't great. Again, slowly, please?"] },
  { id: 'a1-little-english', level: 'A1', place: 'Дверь квартиры', situation: 'Курьер звонит в дверь в семь утра и сыплет вопросами. Глаза ещё не открываются.', who: 'Delivery guy', say: 'Hey! Package for 4B. Is that you? Sign here. Is your neighbor home?',
    phrases: ['I speak a little English', "I'm learning English"],
    samples: ['Sorry, I speak a little English.', "Yes, 4B! I'm learning English. Again, please?", 'Sorry! I speak a little English. One more time?'] },
  { id: 'a1-miss-family', level: 'A1', place: 'Дом', situation: 'Сэм видит, как ты грустно листаешь фото из дома.', who: 'Sam', say: "Hey, you okay? Who's that in the photo?",
    phrases: ['I miss my family', 'I have a brother'],
    samples: ["That's my brother. I miss my family.", "I have a brother — that's him! I miss my family.", "I'm okay. I miss my family."] },
  { id: 'a1-hungry', level: 'A1', place: 'Кухня', situation: 'Полночь. В холодильнике — один огурец и кетчуп. На кухню заходит сосед.', who: 'Roommate', say: 'Why are you in the kitchen at midnight?',
    phrases: ["I'm hungry", "Let's eat!"],
    samples: ["I'm hungry! Pizza?", "I'm hungry. The pizza place is open. Let's eat!", "Shh! I'm hungry."] },
  { id: 'a1-free-sunday', level: 'A1', place: 'Сообщения', situation: 'Джесс зовёт на пикник, а свободный день у тебя всего один.', who: 'Jess (text)', say: 'Picnic in the park! Saturday or Sunday?',
    phrases: ["I'm free on Sunday", 'See you at five'],
    samples: ["I'm free on Sunday!", "Saturday, no. I'm free on Sunday. See you at five?", 'Sunday! See you at five!'] },
  /* ---------- Пакет A1, часть 2: дом и соседи, магазин, здоровье, звонки ---------- */
  { id: 'a1-new-neighbor', level: 'A1', place: 'Лестничная площадка', situation: 'Дверь напротив открылась: соседка с котом на руках смотрит с интересом.', who: 'Neighbor', say: 'Oh! Hi there. Are you new?',
    phrases: ["Hi, I'm your new neighbor", 'I live on the fifth floor'],
    samples: ["Hi, I'm your new neighbor!", "Yes! Hi, I'm your new neighbor. I live on the fifth floor.", "I live on the fifth floor. Hi, I'm your new neighbor!"] },
  { id: 'a1-laundry', level: 'A1', place: 'Подвал дома', situation: 'В руках гора грязной одежды, а где стиральные машины — непонятно. Мимо идёт Мэгги.', who: 'Maggie', say: "Whoa, that's a lot of clothes!",
    phrases: ["Where's the laundry room?"],
    samples: ["I know! Where's the laundry room?", "Ha! Where's the laundry room?", "Help! Where's the laundry room?"] },
  { id: 'a1-cold-shower', level: 'A1', place: 'Ванная', situation: 'Утро, голова в пене — и из душа вдруг пошла ледяная вода. Звонок арендодателю.', who: 'Mr. Okafor (phone)', say: 'Good morning. This is Mr. Okafor. How may I help you?',
    phrases: ["The shower doesn't work", "It's so cold in here"],
    samples: ["Good morning! The shower doesn't work.", "Hi! The shower doesn't work, and it's so cold in here.", "Help! It's so cold in here!"] },
  { id: 'a1-loud-music', level: 'A1', place: 'Квартира', situation: 'Полночь. За стеной сосед включил музыку на полную. Стук в его дверь — он открывает.', who: 'Neighbor', say: "Hey! What's up?",
    phrases: ['Can you turn the music down?', "It's too loud"],
    samples: ['Hi! Can you turn the music down?', "Sorry, it's too loud. Can you turn the music down?", "It's midnight, and it's too loud!"] },
  { id: 'a1-sugar', level: 'A1', place: 'Дверь соседей', situation: 'Торт для Мэгги почти готов, а сахар кончился. Стук к соседке напротив.', who: 'Neighbor', say: 'Oh, hi! Can I help you?',
    phrases: ['Can I borrow some sugar?'],
    samples: ['Hi! Can I borrow some sugar?', "Sorry, can I borrow some sugar? It's for a cake.", 'Yes! Can I borrow some sugar, please?'] },
  { id: 'a1-package', level: 'A1', place: 'Подъезд', situation: 'У твоей двери лежит чужая посылка. По лестнице поднимается сосед.', who: 'Neighbor', say: 'Hi! Is that box for me?',
    phrases: ['Is this your package?'],
    samples: ['Hi! Is this your package?', 'Maybe! Is this your package? It was at my door.', "Is this your package? It's heavy!"] },
  { id: 'a1-bathroom-line', level: 'A1', place: 'Квартира', situation: 'Утро, пора бежать на работу, а в ванной уже двадцать минут кто-то поёт.', who: 'Sam (in the bathroom)', say: 'Almost done! Two more minutes!',
    phrases: ['Is the bathroom free?', "I'm late!"],
    samples: ["Is the bathroom free now? I'm late!", "Sam! I'm late!", "Hey, is the bathroom free? I'm late!"] },
  { id: 'a1-elevator', level: 'A1', place: 'Подъезд', situation: 'Лифт сломан, а у тебя три тяжёлые коробки и пятый этаж. Мимо идёт Рэй.', who: 'Ray', say: 'Whoa, need some help?',
    phrases: ['Can you help me with this box?', 'The elevator is broken'],
    samples: ['Yes, please! Can you help me with this box?', 'The elevator is broken. Can you help me with this box?', 'Thanks! The elevator is broken.'] },
  { id: 'a1-store-bread', level: 'A1', place: 'Магазин у дома', situation: 'Магазин огромный, хлеба нигде не видно. Луис раскладывает товар на полке.', who: 'Luis', say: 'Hi! Finding everything okay?',
    phrases: ["Where's the bread?", 'Do you have eggs?'],
    samples: ["Hi! Where's the bread?", "Almost! Where's the bread? And do you have eggs?", "Do you have eggs? And where's the bread?"] },
  { id: 'a1-jacket-size', level: 'A1', place: 'Магазин одежды', situation: 'Куртка мечты, но рукава закрывают пальцы.', who: 'Sales assistant', say: 'How is it? Looks great!',
    phrases: ["It's too big", 'Do you have a smaller one?'],
    samples: ["Hmm, it's too big.", "It's too big. Do you have a smaller one?", 'I love it! Do you have a smaller one?'] },
  { id: 'a1-pay-cash', level: 'A1', place: 'Касса', situation: 'Терминал для карт сломался, а очередь сзади растёт. У тебя есть наличные.', who: 'Luis', say: 'Sorry, the card machine is down.',
    phrases: ['Can I pay with cash?', 'Here you go'],
    samples: ['Okay. Can I pay with cash?', 'Can I pay with cash? Here you go.', 'Here you go — twenty dollars.'] },
  { id: 'a1-line', level: 'A1', place: 'Магазин', situation: 'Две кассы, две толпы, и где чья очередь — непонятно.', who: 'Shopper', say: 'Excuse me, are you waiting?',
    phrases: ['Is this the line?', 'Where do I pay?'],
    samples: ['Yes! Is this the line?', 'I think so. Is this the line?', 'Sorry, where do I pay? Is this the line?'] },
  { id: 'a1-gift', level: 'A1', place: 'Магазин подарков', situation: 'Выбран подарок Мэгги на день рождения. Кассир тянется за пакетом.', who: 'Cashier', say: 'Do you want a bag?',
    phrases: ["It's a gift", "I don't need a bag"],
    samples: ["It's a gift! Can you wrap it?", "I don't need a bag, thanks. It's a gift.", "I don't need a bag, thanks."] },
  { id: 'a1-discount', level: 'A1', place: 'Магазин электроники', situation: 'Наушники стоят пятьдесят долларов, а в кармане студенческий.', who: 'Sales assistant', say: 'These are fifty dollars.',
    phrases: ['Can I get a discount?', "I'm a student"],
    samples: ["I'm a student. Can I get a discount?", 'Hmm. Can I get a discount?', "Can I get a discount? I'm a student!"] },
  { id: 'a1-return', level: 'A1', place: 'Магазин', situation: 'Футболка села после первой стирки. Возврат на кассе.', who: 'Cashier', say: "Hi! What's the problem?",
    phrases: ["It's too small", "Here's my receipt"],
    samples: ["It's too small now. Here's my receipt.", "This shirt — it's too small. Here's my receipt.", "Here's my receipt. It's too small."] },
  { id: 'a1-feel-sick', level: 'A1', place: 'Офис', situation: 'Голова кружится, всё плывёт. Прия замечает, что что-то не так.', who: 'Priya', say: 'Hey, you look pale. What happened?',
    phrases: ['I feel sick', 'I need to lie down'],
    samples: ['I feel sick.', 'Honestly, I feel sick. I need to lie down.', 'I need to lie down for a minute.'] },
  { id: 'a1-drugstore', level: 'A1', place: 'Аптека', situation: 'Простуда, красный нос. Фармацевт спрашивает, чем помочь.', who: 'Pharmacist', say: 'Hi! What can I do for you?',
    phrases: ['I have a cold', 'I need some medicine'],
    samples: ['I have a cold.', 'I have a cold. I need some medicine.', 'Hi! I need some medicine for a cold.'] },
  { id: 'a1-tooth', level: 'A1', place: 'Офис', situation: 'Ужасно болит зуб. Тони зовёт всех на пиццу.', who: 'Tony', say: 'Pizza for lunch? My treat!',
    phrases: ['My tooth hurts'],
    samples: ['Sorry, my tooth hurts.', 'Ugh, my tooth hurts. Maybe soup?', 'My tooth hurts! Next time.'] },
  { id: 'a1-sick-day', level: 'A1', place: 'Телефон', situation: 'Утро, температура 38. Нужно предупредить Прию, что на работу сегодня никак.', who: 'Priya (phone)', say: 'Good morning! See you at nine?',
    phrases: ["I'm sick today", 'I have a fever'],
    samples: ["Sorry, I'm sick today.", "I'm sick today. I have a fever.", "I have a fever. I'm sick today, sorry."] },
  { id: 'a1-allergy', level: 'A1', place: 'В гостях', situation: 'У Сэма дома три кота, и глаза уже чешутся.', who: 'Sam', say: 'Meet my cats! Want to hold one?',
    phrases: ["I'm allergic to cats"],
    samples: ["Sorry, I'm allergic to cats.", "They're cute, but I'm allergic to cats.", "Oh, I'm allergic to cats!"] },
  { id: 'a1-call-noise', level: 'A1', place: 'Улица', situation: 'Звонит Джесс, а рядом грохочет поезд надземки.', who: 'Jess (phone)', say: 'Hi! So, about tonight...',
    phrases: ["I can't hear you", 'Call me later'],
    samples: ["Sorry, I can't hear you!", "I can't hear you. Call me later!", "Call me later, okay? It's so loud here."] },
  { id: 'a1-outside', level: 'A1', place: 'У подъезда', situation: 'Вечеринка у Сэма, а звонок в домофон не работает.', who: 'Sam (text)', say: 'Where are you? The party started!',
    phrases: ["I'm outside"],
    samples: ["I'm outside!", "I'm outside. The doorbell is broken.", "Come down! I'm outside."] },
  { id: 'a1-good-time', level: 'A1', place: 'Телефон', situation: 'Звонок Тони по рабочему вопросу, а у него на фоне шум и лай собаки.', who: 'Tony (phone)', say: 'Hello? Hey!',
    phrases: ['Is this a good time?', "I'll call you tomorrow"],
    samples: ['Hi! Is this a good time?', "Is this a good time? Or I'll call you tomorrow.", "Oh, it's loud. I'll call you tomorrow!"] },
  { id: 'a1-new-number', level: 'A1', place: 'Сообщения', situation: 'Новая американская сим-карта, и друзья не знают номер. Сообщение Мэгги.', who: 'Maggie (text)', say: 'Who is this??',
    phrases: ['My number is new', "It's me, Alex"],
    samples: ["It's me, Alex! My number is new.", 'Hi! My number is new.', "It's me, Alex. Save this number!"] },
  { id: 'a1-awake', level: 'A1', place: 'Сообщения', situation: 'Час ночи, сна ни в одном глазу. Сообщение Джесс — вдруг она тоже не спит.', who: 'Jess (text)', say: 'Hey... what\'s up?',
    phrases: ['Are you awake?', "I can't sleep"],
    samples: ["Are you awake? I can't sleep.", "I can't sleep. Want to talk?", 'Hey! Are you awake?'] },
  /* ---------- Пакет A1+, часть 1: «Первый месяц» — планы, хочу и надо, вопросы ---------- */
  { id: 'a1p-late-subway', level: 'A1+', place: 'Метро', situation: 'Поезд встал в туннеле, а Прия ждёт на планёрке через десять минут.', who: 'Priya (text)', say: 'Morning! See you at nine?',
    phrases: ["I'm gonna be late", 'I gotta go'],
    samples: ["Sorry, I'm gonna be late. The train is stuck.", "I'm gonna be late! Ten minutes.", "I'm gonna be late, sorry! I gotta go."] },
  { id: 'a1p-day-off', level: 'A1+', place: 'Кухня', situation: 'Мэгги узнала, что у тебя завтра выходной, и уже строит планы.', who: 'Maggie', say: "You're off tomorrow? What's the plan?",
    phrases: ["Let's go somewhere", "I'm gonna stay home"],
    samples: ["I'm gonna stay home and sleep.", "Let's go somewhere! The beach?", "Let's go somewhere fun."] },
  { id: 'a1p-rain-picnic', level: 'A1+', place: 'Парк', situation: 'Пикник с Джесс, а небо всё темнее.', who: 'Jess', say: 'Look at the sky! Should we stay?',
    phrases: ["It's gonna rain", 'Maybe next time'],
    samples: ["Hmm, it's gonna rain.", "It's gonna rain. Maybe next time!", "Let's go home. Maybe next time."] },
  { id: 'a1p-nervous-friend', level: 'A1+', place: 'Кафе', situation: 'Завтра у вас с Тони общая презентация. Он крутит стакан и нервничает.', who: 'Tony', say: "I'm so nervous about tomorrow...",
    phrases: ["We're gonna be fine", "It's gonna be great"],
    samples: ["Relax! It's gonna be great.", "We're ready. It's gonna be great!", "Come on, we're gonna be fine."] },
  { id: 'a1p-weekend', level: 'A1+', place: 'Офис', situation: 'Пятница, вечер. Коллега спрашивает про выходные.', who: 'Coworker', say: 'Big plans for Saturday?',
    phrases: ['Nothing much', "I'm gonna stay home"],
    samples: ["Nothing much. I'm gonna stay home.", 'Nothing much, really.', "Honestly? I'm gonna stay home and sleep."] },
  { id: 'a1p-meet-time', level: 'A1+', place: 'Сообщения', situation: 'Сэм зовёт на баскетбол, но не сказал, когда.', who: 'Sam (text)', say: 'Basketball tomorrow?? You in?',
    phrases: ['What time are we meeting?', 'Tomorrow works'],
    samples: ['Yes! What time are we meeting?', 'Tomorrow works! What time are we meeting?', 'Tomorrow works for me.'] },
  { id: 'a1p-party-who', level: 'A1+', place: 'Подъезд', situation: 'Соседка зовёт на вечеринку на крыше, а ты почти никого не знаешь.', who: 'Neighbor', say: 'Rooftop party tonight! Come!',
    phrases: ["Who's gonna be there?", "I'm gonna be there"],
    samples: ["Cool! Who's gonna be there?", "Sounds fun. Who's gonna be there?", "Okay, I'm gonna be there!"] },
  { id: 'a1p-cook', level: 'A1+', place: 'Квартира', situation: 'Мэгги собирается опять заказывать пиццу — третий раз за неделю.', who: 'Maggie', say: 'Pizza again tonight?',
    phrases: ["I'm gonna cook tonight"],
    samples: ["Hmm... I'm gonna cook tonight!", "Wait! I'm gonna cook tonight.", "I'm gonna cook tonight. Pasta?"] },
  { id: 'a1p-gotta-go', level: 'A1+', place: 'Улица', situation: 'Болтливый сосед рассказывает про свою кошку уже двадцать минут.', who: 'Neighbor', say: '...and then my cat jumps on the fridge!',
    phrases: ['I gotta go', "I'm gonna be late"],
    samples: ["Ha! Sorry, I gotta go.", "Wow! Okay, I gotta go. I'm gonna be late.", "I gotta go — see you around!"] },
  { id: 'a1p-lunch', level: 'A1+', place: 'Офис', situation: 'Полдень. Желудок урчит, Тони смотрит на часы.', who: 'Tony', say: "Ugh, I'm starving.",
    phrases: ['Wanna grab lunch?', 'What do you wanna eat?'],
    samples: ['Me too! Wanna grab lunch?', 'Wanna grab lunch? What do you wanna eat?', 'Same. What do you wanna eat?'] },
  { id: 'a1p-try-this', level: 'A1+', place: 'Фудкорт', situation: 'На фудкорте нашлась лучшая лапша в городе, а Джесс ест сухой салат.', who: 'Jess', say: 'What is that? It smells amazing.',
    phrases: ['You gotta try this', 'Want some?'],
    samples: ['Noodles! You gotta try this.', 'You gotta try this! Want some?', 'Want some? Take a fork!'] },
  { id: 'a1p-early', level: 'A1+', place: 'Вечеринка', situation: 'Полночь, вечеринка в разгаре, а будильник стоит на шесть.', who: 'Sam', say: 'One more song! Stay!',
    phrases: ['I gotta get up early', 'I gotta go'],
    samples: ['Sorry, I gotta get up early.', 'I gotta go. I gotta get up early!', 'I gotta get up early. Next time!'] },
  { id: 'a1p-break', level: 'A1+', place: 'Офис', situation: 'Третий час подряд таблицы. Тони просит помочь ещё с одной.', who: 'Tony', say: 'Can you help with one more report?',
    phrases: ['I need a break', 'Do I have to?'],
    samples: ['Sure, but I need a break first.', 'Do I have to? I need a break.', 'Okay. I need a break, though.'] },
  { id: 'a1p-help-boxes', level: 'A1+', place: 'Квартира', situation: 'Переезд: коробки повсюду, а Сэм пришёл «просто поздороваться».', who: 'Sam', say: 'Hey! Whoa, so many boxes.',
    phrases: ['Wanna help me?'],
    samples: ['I know! Wanna help me?', 'Hi! Wanna help me? Pizza is on me.', 'Wanna help me with this one?'] },
  { id: 'a1p-movie-night', level: 'A1+', place: 'Квартира', situation: 'Дождливый вечер, Мэгги лежит на диване и вздыхает.', who: 'Maggie', say: "I'm so bored...",
    phrases: ['Wanna watch a movie?', 'I just wanna sleep'],
    samples: ['Wanna watch a movie?', 'Me too. Wanna watch a movie?', 'Honestly, I just wanna sleep.'] },
  { id: 'a1p-gift-no', level: 'A1+', place: 'Подъезд', situation: 'Сосед отдаёт старую лампу. Она тебе точно не нужна.', who: 'Neighbor', say: 'Want this lamp? It still works!',
    phrases: ["I don't need it"],
    samples: ["Thanks, but I don't need it.", "That's nice, but I don't need it.", "Oh, thanks! I don't need it, though."] },
  { id: 'a1p-new-coworker', level: 'A1+', place: 'Офис', situation: 'Первый обед с новой коллегой. Нужно поддержать разговор.', who: 'Coworker', say: 'So... I just moved here from Ohio.',
    phrases: ['Do you like it here?', 'What do you do for fun?'],
    samples: ['Cool! Do you like it here?', 'Nice. What do you do for fun?', 'Do you like it here? What do you do for fun?'] },
  { id: 'a1p-whats-wrong', level: 'A1+', place: 'Кухня', situation: 'Мэгги пришла домой и молча села у окна.', who: 'Maggie', say: 'Ugh...',
    phrases: ["What's wrong?", 'What happened?'],
    samples: ["Hey, what's wrong?", "What happened? What's wrong?", 'Oh no. What happened?'] },
  { id: 'a1p-serious', level: 'A1+', place: 'Кафе', situation: 'Тони вдруг объявляет, что уезжает жить в Калифорнию.', who: 'Tony', say: "I'm moving to California next month!",
    phrases: ['Are you serious?'],
    samples: ['Wait, are you serious?', 'Are you serious? Wow!', 'What? Are you serious? I wanna go!'] },
  { id: 'a1p-time-there', level: 'A1+', place: 'Видеозвонок', situation: 'Сэм звонит из Токио, а у тебя уже ночь.', who: 'Sam (video)', say: 'Hey! Good morning from Tokyo!',
    phrases: ['What time is it there?'],
    samples: ['Good morning? What time is it there?', 'Wow! What time is it there?', "It's night here! What time is it there?"] },
  { id: 'a1p-word-mean', level: 'A1+', place: 'Улица', situation: 'На двери кафе непонятная табличка. Рядом стоит Луис.', who: 'Luis', say: 'Hey! You okay? You look lost.',
    phrases: ['What does it mean?'],
    samples: ['Hi! This sign — what does it mean?', 'Yes! What does it mean?', 'The sign! What does it mean?'] },
  { id: 'a1p-come-too', level: 'A1+', place: 'Офис', situation: 'Коллеги собираются на караоке после работы.', who: 'Tony', say: "We're going to karaoke tonight!",
    phrases: ['Can I come too?', 'Why not?'],
    samples: ['Cool! Can I come too?', "Karaoke? Why not? Can I come too?", 'Why not? Sounds fun!'] },
  { id: 'a1p-nope', level: 'A1+', place: 'Офис', situation: 'Тони спрашивает про общий отчёт, а он ещё не начат.', who: 'Tony', say: 'Did you finish the report?',
    phrases: ['Nope, not yet'],
    samples: ['Nope, not yet. Tomorrow?', 'Nope, not yet. Sorry!', 'Nope, not yet, but almost.'] },
  { id: 'a1p-thats-me', level: 'A1+', place: 'Кофейня', situation: 'Бариста держит стакан и зовёт имя, похожее на твоё.', who: 'Barista', say: 'Alex? Latte for Alex?',
    phrases: ["Yep, that's me"],
    samples: ["Yep, that's me!", "Yep, that's me. Thanks!", "Oh! Yep, that's me."] },
  { id: 'a1p-everybody', level: 'A1+', place: 'Квартира', situation: 'Вечеринка у Сэма должна была начаться час назад, а в квартире пусто.', who: 'Sam (phone)', say: 'Hey! Are you at my place?',
    phrases: ["Where's everybody?"],
    samples: ["Yes! Where's everybody?", "I'm here. Where's everybody?", "It's so quiet. Where's everybody?"] },
  /* ---------- Пакет A1+, часть 2: «Первый месяц» — живая речь, вчера, могу и не могу, мнения, как часто ---------- */
  { id: 'a1p-milk-run', level: 'A1+', place: 'Сообщения', situation: 'Мэгги просит купить молоко по дороге домой.', who: 'Maggie (text)', say: 'Can you grab some milk on the way home?',
    phrases: ['Yeah, no problem'],
    samples: ['Yeah, no problem!', 'Yeah, no problem. Anything else?', 'Milk? Yeah, no problem.'] },
  { id: 'a1p-late-start', level: 'A1+', place: 'Квартира', situation: 'Сэм зашёл за тобой, а ты ещё в одном носке ищешь второй.', who: 'Sam', say: 'Come on! The game starts in ten minutes!',
    phrases: ['Gimme five minutes', "C'mon, let's go!"],
    samples: ['Gimme five minutes! My sock!', "Okay, okay. C'mon, let's go!", 'Gimme five minutes, please!'] },
  { id: 'a1p-bar-noise', level: 'A1+', place: 'Бар', situation: 'Тони зовёт после работы в шумный спортбар. Музыка орёт, все кричат.', who: 'Tony', say: 'This place is great, right?',
    phrases: ["It's a bit loud", 'Nah, not really'],
    samples: ["It's cool, but it's a bit loud.", "Nah, not really. It's a bit loud.", "Hmm, it's a bit loud. Let's go?"] },
  { id: 'a1p-dinner-done', level: 'A1+', place: 'Кафе', situation: 'Джесс принесла добавку картошки фри, а в тебя уже не влезает ни кусочка.', who: 'Jess', say: 'More fries? On the house!',
    phrases: ["Nah, I'm good"],
    samples: ["Nah, I'm good. Thank you!", "Aw! Nah, I'm good.", "Nah, I'm good. Just the check."] },
  { id: 'a1p-leaving-party', level: 'A1+', place: 'Вечеринка', situation: 'Полночь, завтра рано на работу. Сэм уговаривает остаться ещё на часок.', who: 'Sam', say: 'One more song! Stay!',
    phrases: ['Gotta run', "Not now, 'cause it's late"],
    samples: ['Sorry, gotta run!', "Not now, 'cause it's late. Bye!", 'Gotta run. Work tomorrow!'] },
  { id: 'a1p-monday-chat', level: 'A1+', place: 'Офис', situation: 'Понедельник, кухня в офисе. Тони наливает кофе и хочет поболтать про выходные.', who: 'Tony', say: 'So, what did you do this weekend?',
    phrases: ['We went to the beach', 'It was fun'],
    samples: ['Beach day! It was fun!', 'We went to the beach!', 'Oh, we went to the beach. Fun!'] },
  { id: 'a1p-boring-meeting', level: 'A1+', place: 'Офис', situation: 'Прия спрашивает, как прошла встреча с поставщиками. Встреча была два часа ни о чём.', who: 'Priya', say: 'How was the meeting?',
    phrases: ['It was so boring', 'It took forever'],
    samples: ['Honestly? It was so boring.', 'It took forever. Two hours!', 'It was so boring. It took forever.'] },
  { id: 'a1p-cab-late', level: 'A1+', place: 'Такси', situation: 'Рэй ждёт вас с другом у вокзала уже сорок минут: по дороге вы заблудились.', who: 'Ray', say: 'Hey! I waited forever. What happened?',
    phrases: ['We got lost', 'We missed the train'],
    samples: ['Sorry! We got lost.', 'We missed the train. So sorry!', 'We got lost in Brooklyn. Sorry!'] },
  { id: 'a1p-interview-call', level: 'A1+', place: 'Телефон', situation: 'Мэгги звонит узнать, как прошло твоё первое американское собеседование.', who: 'Maggie (phone)', say: 'So? Tell me everything!',
    phrases: ['It went well', 'It was my first time'],
    samples: ['I think it went well!', 'It was my first time. It went well!', 'It went well! It was my first time.'] },
  { id: 'a1p-sick-day', level: 'A1+', place: 'Офис', situation: 'Вчера тебя не было на работе. Прия встречает тебя у лифта.', who: 'Priya', say: 'Hey! We missed you yesterday. Everything okay?',
    phrases: ['I felt sick', "I didn't have time"],
    samples: ['I felt sick. Better now, thanks!', 'Yeah, I felt sick. Sorry!', "Sorry, I didn't have time to call."] },
  { id: 'a1p-chicago-trip', level: 'A1+', place: 'Кафе', situation: 'Джесс узнала про твою поездку в Чикаго и хочет подробностей.', who: 'Jess', say: 'You went to Chicago? How was it?',
    phrases: ['It was so cold', 'I had a great time'],
    samples: ['It was so cold! Great trip.', 'I had a great time!', 'Beautiful. But it was so cold!'] },
  { id: 'a1p-heavy-box', level: 'A1+', place: 'Подъезд', situation: 'Мистер Окафор тащит по лестнице огромную коробку и пыхтит.', who: 'Mr. Okafor', say: 'Oof. This box is so heavy...',
    phrases: ['I can help', 'Can I get you anything?'],
    samples: ['Here, I can help!', 'Wait, I can help.', 'Can I get you anything? Water?'] },
  { id: 'a1p-no-wallet', level: 'A1+', place: 'Магазин', situation: 'На кассе у Луиса выяснилось, что кошелёк остался дома.', who: 'Luis', say: "That's twelve fifty.",
    phrases: ['Can I pay later?'],
    samples: ['Oh no, my wallet! Can I pay later?', 'Sorry! Can I pay later? Tomorrow?', "My wallet... Can I pay later?"] },
  { id: 'a1p-pool-invite', level: 'A1+', place: 'Квартира', situation: 'Мэгги в купальнике тянет тебя в бассейн. А ты не умеешь плавать.', who: 'Maggie', say: 'Pool party! Come on, get your stuff!',
    phrases: ["I can't swim", "Can I try?"],
    samples: ["Hmm, I can't swim.", "Okay... Can I try?", "Honestly, I can't swim."] },
  { id: 'a1p-bank-fast', level: 'A1+', place: 'Банк', situation: 'Мисс Гарсия объясняет условия счёта очень быстро, ты понимаешь каждое третье слово.', who: 'Ms. Garcia', say: 'So, the monthly fee is zero if you keep five hundred dollars...',
    phrases: ['Can you speak more slowly?'],
    samples: ['Sorry, can you speak more slowly?', 'Can you speak more slowly, please?', 'Wait, wait. Can you speak more slowly?'] },
  { id: 'a1p-party-no', level: 'A1+', place: 'Сообщения', situation: 'Сэм зовёт на вечеринку сегодня, а у тебя завтра в семь утра смена.', who: 'Sam (text)', say: 'Party at my place tonight!! 🎉',
    phrases: ["I can't come tonight"],
    samples: ["Sorry, I can't come tonight.", "Aw, I can't come tonight. Next time!", "I can't come tonight. Work tomorrow!"] },
  { id: 'a1p-haircut', level: 'A1+', place: 'Кухня', situation: 'Мэгги вернулась из парикмахерской с ярко-розовыми волосами и ждёт твоего мнения.', who: 'Maggie', say: 'So? What do you think? Be honest!',
    phrases: ['I like it', 'It looks great'],
    samples: ['Wow! I like it!', 'It looks great! Very cool.', 'I like it! It looks great.'] },
  { id: 'a1p-hot-sauce', level: 'A1+', place: 'Ресторан', situation: 'Тони протягивает тебе свой фирменный соус «Адское пламя».', who: 'Tony', say: 'Try my hot sauce! It\'s amazing!',
    phrases: ["I don't like spicy food", 'Not for me'],
    samples: ["Thanks, but I don't like spicy food.", 'Ha! Not for me, thanks.', "No thanks. I don't like spicy food."] },
  { id: 'a1p-two-phones', level: 'A1+', place: 'Магазин', situation: 'Луис показывает два телефона по акции и ждёт, какой ты выберешь.', who: 'Luis', say: 'This one or this one?',
    phrases: ['Which one is better?', "It's too expensive"],
    samples: ['Hmm. Which one is better?', "Which one is better? This one's too expensive.", "That one? It's too expensive."] },
  { id: 'a1p-jazz-night', level: 'A1+', place: 'Офис', situation: 'Прия зовёт команду на джазовый вечер. Ты не любишь джаз, но Прия — начальница.', who: 'Priya', say: 'Jazz night on Friday! Who\'s in?',
    phrases: ["I'm not a fan"],
    samples: ["Honestly, I'm not a fan. But okay!", "Jazz? I'm not a fan, sorry.", "Honestly, I'm not a fan. Sorry!"] },
  { id: 'a1p-gym-often', level: 'A1+', place: 'Спортзал', situation: 'Тони записался в спортзал и хочет узнать, как часто ты тренируешься.', who: 'Tony', say: 'How often do you go to the gym?',
    phrases: ['Once a week', 'Not very often'],
    samples: ['Once a week. Saturdays.', 'Not very often, honestly.', 'Not very often. Once a week, maybe.'] },
  { id: 'a1p-always-late', level: 'A1+', place: 'Кафе', situation: 'Встреча с Джесс, а ты снова на пятнадцать минут позже.', who: 'Jess', say: 'Fifteen minutes! Again!',
    phrases: ["I'm always late", 'Every time'],
    samples: ["Sorry! I'm always late.", "I know, I know. I'm always late.", "Every time, I know! Sorry!"] },
  { id: 'a1p-cooking', level: 'A1+', place: 'Кухня', situation: 'Сэм заглянул на ужин и удивился пустому холодильнику.', who: 'Sam', say: 'Wait... do you ever cook?',
    phrases: ['I never cook', 'Almost never'],
    samples: ['Ha! I never cook.', 'Almost never. I order in.', 'Honestly? Almost never.'] },
  { id: 'a1p-landlord-noise', level: 'A1+', place: 'Подъезд', situation: 'Мистер Окафор спрашивает, часто ли соседи сверху шумят по ночам.', who: 'Mr. Okafor', say: 'Is the noise upstairs a problem?',
    phrases: ['All the time', 'Every night'],
    samples: ['Yes! All the time.', 'Every night, after midnight.', 'All the time! Every night!'] },
  { id: 'a1p-subway-stop', level: 'A1+', place: 'Метро', situation: 'Поезд снова встал между станциями. Турист рядом нервно смотрит на тебя.', who: 'Tourist', say: 'Is this normal? We stopped!',
    phrases: ['It happens a lot', "Nah, it's fine"],
    samples: ["Don't worry, it happens a lot.", "Nah, it's fine. It happens a lot.", "It happens a lot. Two minutes."] },
  /* ---------- Пакет A2, часть 1: «Что было» — рассказать о прошлом (Past Simple, вопросы с did, реакции) ---------- */
  { id: 'a2-monday', level: 'A2', place: 'Офис', situation: 'Понедельник, кофемашина. Тони спрашивает про выходные — а у вас был поход за город.', who: 'Tony', say: 'Hey! How was your weekend?',
    phrases: ['We went hiking', 'We had a blast'],
    samples: ['Great! We went hiking upstate.', 'We went hiking. We had a blast!', 'Awesome. We went hiking on Saturday.'] },
  { id: 'a2-late-train', level: 'A2', place: 'Офис', situation: 'Ты опаздываешь на сорок минут. Прия смотрит на часы. Причина — сломался поезд метро.', who: 'Priya', say: 'Everything okay? You\'re really late.',
    phrases: ['The subway broke down'],
    samples: ['So sorry! The subway broke down.', 'The subway broke down. It was a nightmare.', 'Sorry! The subway broke down again.'] },
  { id: 'a2-no-call', level: 'A2', place: 'Улица', situation: 'Мэгги час ждала у кинотеатра, а у вашей машины по дороге сел аккумулятор.', who: 'Maggie', say: 'Where were you? I called five times!',
    phrases: ['The battery died'],
    samples: ['Sorry! The battery died.', 'The battery died on the highway. Sorry!', 'Ugh, the battery died. Long story.'] },
  { id: 'a2-story-start', level: 'A2', place: 'Кафе', situation: 'Вчера Сэм уронил торт прямо на начальника. Джесс ещё не знает — расскажи с интригой.', who: 'Jess', say: 'So what\'s new?',
    phrases: ['Guess what happened', 'You won\'t believe this'],
    samples: ['Guess what happened yesterday!', 'You won\'t believe this. Sam dropped a cake!', 'Okay, guess what happened at work.'] },
  { id: 'a2-wedding', level: 'A2', place: 'Сообщения', situation: 'Ким вернулась со свадьбы подруги. Спроси, как всё прошло.', who: 'Kim (text)', say: 'Back from the wedding! Soooo tired.',
    phrases: ['How was the wedding?', 'Did you have fun?'],
    samples: ['Welcome back! How was the wedding?', 'Did you have fun?', 'How was the wedding? Did you have fun?'] },
  { id: 'a2-quiet', level: 'A2', place: 'Офис', situation: 'Коллега спрашивает про выходные, а вы с соседями просто сидели дома.', who: 'Coworker', say: 'Do anything fun this weekend?',
    phrases: ['We stayed in', 'Just a quiet weekend'],
    samples: ['Not really. We stayed in.', 'Just a quiet weekend. We stayed in.', 'We stayed in and watched movies.'] },
  { id: 'a2-locked-out', level: 'A2', place: 'Подъезд', situation: 'Вы с Мэгги сидите на лестнице: ключи остались в квартире. Мистер Окафор идёт мимо.', who: 'Mr. Okafor', say: 'Why are you sitting on the stairs?',
    phrases: ['We locked ourselves out'],
    samples: ['We locked ourselves out!', 'Ugh, we locked ourselves out. Do you have a key?', 'Long story... we locked ourselves out.'] },
  { id: 'a2-react-job', level: 'A2', place: 'Кафе', situation: 'Джесс полгода искала работу — и её наконец взяли.', who: 'Jess', say: 'I got the job!!',
    phrases: ['You did it!', 'About time!'],
    samples: ['You did it! Congrats!', 'About time! You did it!', 'Wow, you did it! When do you start?'] },
  { id: 'a2-react-bike', level: 'A2', place: 'Улица', situation: 'Сэм грустный: ночью у него украли велосипед.', who: 'Sam', say: 'Someone stole my bike last night.',
    phrases: ["That's awful", 'What a nightmare'],
    samples: ["Wow, that's awful!", "That's awful. What a nightmare!", "Seriously? That's awful."] },
  { id: 'a2-follow-up', level: 'A2', place: 'Кафе', situation: 'Тони рассказывает, как застрял в лифте, и замолкает на самом интересном месте.', who: 'Tony', say: '...and then the lights went out.',
    phrases: ['What happened next?', 'Then what?'],
    samples: ['Whoa! What happened next?', 'Wait. Then what?', 'Seriously? Then what?'] },
  { id: 'a2-when-back', level: 'A2', place: 'Подъезд', situation: 'Соседка, которую не было две недели, тащит чемодан к лифту.', who: 'Neighbor', say: 'Hi! I was in Mexico!',
    phrases: ['When did you get back?', 'Did you have fun?'],
    samples: ['Nice! When did you get back?', 'Mexico! Did you have fun?', 'Cool! When did you get back?'] },
  { id: 'a2-cost', level: 'A2', place: 'Квартира', situation: 'Мэгги хвастается новым диваном. Тебе интересно, сколько он стоил.', who: 'Maggie', say: 'Look! New couch!',
    phrases: ['How much did it cost?', 'Where did you buy that?'],
    samples: ['Nice! How much did it cost?', 'Love it! Where did you buy that?', 'Wow. How much did it cost?'] },
  { id: 'a2-flight', level: 'A2', place: 'Аэропорт', situation: 'Ты пишешь Рэю, что не прилетишь вовремя: рейс задержали на три часа.', who: 'Ray (text)', say: 'I\'m at JFK. Where are you?',
    phrases: ['The flight got delayed'],
    samples: ['Sorry! The flight got delayed.', 'The flight got delayed. Three hours!', 'Ugh, the flight got delayed. I\'ll text you.'] },
  { id: 'a2-long-story', level: 'A2', place: 'Кухня', situation: 'Мэгги спрашивает, почему вы с Сэмом вернулись в три ночи. История длинная — расскажи коротко.', who: 'Maggie', say: 'Three a.m.? What happened?',
    phrases: ['So basically', 'In the end'],
    samples: ['So basically, we missed the last train.', 'Long night. In the end, we took a cab.', 'So basically, we got lost. In the end, it was fine.'] },
  { id: 'a2-sleep', level: 'A2', place: 'Кухня', situation: 'Утро. Сэм ночевал у вас на диване и выглядит помятым.', who: 'Sam', say: 'Morning...',
    phrases: ['Did you sleep well?'],
    samples: ['Morning! Did you sleep well?', 'Hey! Did you sleep well?', 'Coffee? Did you sleep well?'] },
  { id: 'a2-luckily', level: 'A2', place: 'Офис', situation: 'Прия спрашивает, успели ли вы на самолёт. Вы опоздали, но рейс тоже задержали.', who: 'Priya', say: 'Did you make your flight?',
    phrases: ['Luckily', 'It turned out'],
    samples: ['Luckily, it was delayed!', 'We were late. Luckily, it was delayed.', 'It turned out the flight was late too!'] },
  { id: 'a2-coincidence', level: 'A2', place: 'Вечеринка', situation: 'Выясняется, что новый знакомый был на том же концерте, что и вы с Ким.', who: 'Guest', say: 'Last Friday? I was at that concert too!',
    phrases: ['What a coincidence!'],
    samples: ['No way! What a coincidence!', 'What a coincidence! Great show, right?', 'Really? What a coincidence!'] },
  { id: 'a2-pipe', level: 'A2', place: 'Квартира', situation: 'Ночью прорвало трубу, вода на полу. Звонишь мистеру Окафору.', who: 'Mr. Okafor (phone)', say: 'Hello? It\'s midnight!',
    phrases: ['The pipe burst'],
    samples: ['Sorry! The pipe burst!', 'The pipe burst. Water everywhere!', 'Mr. Okafor, the pipe burst in the kitchen.'] },
  { id: 'a2-nobody-told', level: 'A2', place: 'Офис', situation: 'Утром у тебя встреча с Тони, а её, оказывается, провели вчера. Тони удивлён, что тебе никто не сказал.', who: 'Tony', say: 'The meeting? It was yesterday!',
    phrases: ['Nobody told me'],
    samples: ['What? Nobody told me!', 'Seriously? Nobody told me.', 'Wait, nobody told me!'] },
  { id: 'a2-sounds-fun', level: 'A2', place: 'Кафе', situation: 'Джесс рассказывает, как каталась на каяке по Гудзону.', who: 'Jess', say: 'We went kayaking on the Hudson!',
    phrases: ['Sounds like fun', 'Who did you go with?'],
    samples: ['Sounds like fun! Who did you go with?', 'Wow, sounds like fun!', 'Who did you go with?'] },
  { id: 'a2-first-of-all', level: 'A2', place: 'Сообщения', situation: 'Ким спрашивает, как прошла поездка в Бостон. Отель был отличный, а еда — так себе.', who: 'Kim (text)', say: 'How was Boston???',
    phrases: ['First of all', 'Unfortunately'],
    samples: ['First of all, the hotel was amazing!', 'Great! Unfortunately, the food was meh.', 'First of all, the hotel was great. Unfortunately, it rained.'] },
  { id: 'a2-tattoo', level: 'A2', place: 'Улица', situation: 'Сэм показывает новую татуировку на руке.', who: 'Sam', say: 'Check it out! New tattoo!',
    phrases: ['Did it hurt?'],
    samples: ['Whoa! Did it hurt?', 'Cool! Did it hurt?', 'Nice. Did it hurt a lot?'] },
  { id: 'a2-explains', level: 'A2', place: 'Кухня', situation: 'Мэгги весь день злая. Оказалось, она не спала из-за соседской собаки.', who: 'Maggie', say: 'Sorry I\'m grumpy. The dog barked all night.',
    phrases: ['That explains it', 'Poor thing'],
    samples: ['Oh, that explains it!', 'Aw, poor thing. That explains it.', 'All night? That explains it.'] },
  { id: 'a2-blast', level: 'A2', place: 'Офис', situation: 'Прия спрашивает про корпоратив, на котором её не было. Было очень весело.', who: 'Priya', say: 'How was the party Friday?',
    phrases: ['We had a blast', 'It went by so fast'],
    samples: ['We had a blast!', 'Great! It went by so fast.', 'We had a blast. It went by so fast!'] },
  { id: 'a2-everything-wrong', level: 'A2', place: 'Квартира', situation: 'Мэгги спрашивает про собеседование. Всё пошло не так: опоздание, кофе на рубашке.', who: 'Maggie', say: 'So? How did the interview go?',
    phrases: ['Everything went wrong'],
    samples: ['Ugh, everything went wrong.', 'Everything went wrong. Coffee on my shirt!', 'Don\'t ask. Everything went wrong.'] },
];

const YES_AND_STORIES = [
  { id: 'snake', title: 'Сосед со змеёй', ru: 'Соседка делится странной новостью про нового соседа.', turns: [
    { say: 'So, I just met our new neighbor... he has a pet snake.', samples: ['No way! A real snake? How big is it?', 'Yikes! Does it live in his apartment?'] },
    { say: 'Yeah, and he asked me to watch it this weekend.', samples: ["And you said yes? You're braver than me!", 'Wait, what did you say?'] },
    { say: 'I said yes. So... want to help me?', samples: ['Ha! Count me out!', "Okay, but I'm not touching it!"] },
  ] },
  { id: 'lost-phone', title: 'Потерянный телефон', ru: 'Друг потерял телефон в такси.', turns: [
    { say: 'I left my phone in a cab last night.', samples: ['Oh no! Did you call the cab company?', 'Seriously? How are you texting me then?'] },
    { say: 'The driver called me this morning. He found it!', samples: ["That's amazing! What a nice guy.", 'Wow, lucky you! Did you give him a tip?'] },
    { say: "He wants to bring it over... but he's in New Jersey.", samples: ["Ha! Maybe you should meet halfway.", "That's a long drive. Buy him lunch!"] },
  ] },
  { id: 'boss-surprise', title: 'Сюрприз для начальника', ru: 'Коллега придумал сюрприз на день рождения начальника.', turns: [
    { say: "Let's throw a surprise party for the boss tomorrow!", samples: ["I'm in! What should we bring?", 'Love it! Does anyone know what cake she likes?'] },
    { say: 'Great. You can keep her busy for an hour.', samples: ["Me? Okay, I'll ask her about the budget. That takes forever.", 'Ha, okay. I\'ll schedule a "quick" meeting.'] },
    { say: "Uh-oh... she's walking this way right now!", samples: ['Act natural! Talk about the weather!', "Quick, hide the balloons!"] },
  ] },
  { id: 'pizza', title: 'Пицца в три ночи', ru: 'Соседка не может уснуть и хочет есть.', turns: [
    { say: "I can't sleep. I'm starving.", samples: ["Same. Let's order a pizza.", 'Me too! Is anything still open?'] },
    { say: 'The only place open has pineapple pizza.', samples: ["Honestly? I'm okay with that.", 'Ugh, fine. Hunger wins.'] },
    { say: "They say it'll take two hours.", samples: ["Two hours? Let's just make toast.", "Okay, plan B: cereal."] },
  ] },
  { id: 'wrong-text', title: 'Не тому человеку', ru: 'Коллега отправил сообщение не в тот чат.', turns: [
    { say: 'I just sent a text about my boss... to my boss.', samples: ['Oh no! What did it say?', 'Yikes. Can you delete it?'] },
    { say: 'It said: "She is so slow on Mondays."', samples: ['Hmm. Maybe say it was a joke?', "Well... at least it's true?"] },
    { say: 'She just replied: "Tuesdays too."', samples: ['Ha! She has a sense of humor!', 'Okay, that was actually funny.'] },
  ] },
  { id: 'celebrity', title: 'Встреча со звездой', ru: 'Друг увидел знаменитость в метро.', turns: [
    { say: 'I just saw a famous actor on the subway!', samples: ['No way! Did you talk to him?', 'Seriously? Who was it?'] },
    { say: 'I asked for a photo, and he said yes!', samples: ['That\'s amazing! Send it to me!', 'Lucky you! Was he nice?'] },
    { say: 'But my phone died right before the photo.', samples: ['Oh no! That\'s so sad.', 'Ha! Classic. So no proof?'] },
  ] },
  { id: 'vacation', title: 'Отпуск мечты', ru: 'Друг планирует отпуск.', turns: [
    { say: "I'm taking two weeks off next month!", samples: ['Nice! Where are you going?', 'Lucky you! Any plans?'] },
    { say: "I'm thinking about Iceland. Hot springs, northern lights...", samples: ["That sounds amazing! Isn't it super cold?", "Wow! Can I come with you?"] },
    { say: 'The only problem: I hate the cold.', samples: ['Ha! Then maybe Hawaii?', "Pack a lot of sweaters, I guess!"] },
  ] },
  { id: 'office-cat', title: 'Кот на работе', ru: 'В офис кто-то принёс кота.', turns: [
    { say: "There's a cat in the office today.", samples: ['What? Whose cat is it?', 'No way! Is it friendly?'] },
    { say: "It's sleeping on the manager's keyboard.", samples: ["Ha! Best employee ever.", "Somebody take a picture!"] },
    { say: 'And it just sent an email to the whole company.', samples: ["Ha! What did it say?", "That's the best email this year."] },
  ] },
  { id: 'bad-date', title: 'Неудачное свидание', ru: 'Подруга рассказывает о свидании.', turns: [
    { say: 'My date last night was a disaster.', samples: ['Oh no! What happened?', 'Really? Tell me everything!'] },
    { say: 'He talked about his ex for two hours.', samples: ['Two hours? Yikes!', "That's a red flag."] },
    { say: 'Then he asked me out again.', samples: ["Ha! And what did you say?", "Please tell me you said no."] },
  ] },
  { id: 'coffee-machine', title: 'Новая кофемашина', ru: 'В офисе поставили новую кофемашину.', turns: [
    { say: 'We got a new coffee machine in the kitchen!', samples: ['Finally! Is it any good?', 'Nice! Does it make lattes?'] },
    { say: 'It has fifty buttons and no instructions.', samples: ['Ha! Good luck with that.', "I'll just press them all."] },
    { say: 'Tony pressed one and now it only makes hot chocolate.', samples: ["Honestly, I'm not mad about that.", 'Classic Tony!'] },
  ] },
  { id: 'movie-fight', title: 'Спор о кино', ru: 'Друг выбирает фильм на вечер.', turns: [
    { say: "Let's watch a horror movie tonight!", samples: ['Hmm, maybe a comedy instead?', "Okay, but I'm sleeping with the lights on."] },
    { say: "Come on, it's not that scary.", samples: ["That's what you said last time.", "Fine, but you're making popcorn."] },
    { say: "Okay... I'm actually too scared to watch it alone.", samples: ['Ha! I knew it!', 'Fine, comedy it is.'] },
  ] },
  { id: 'marathon', title: 'Марафон', ru: 'Друг решил пробежать марафон.', turns: [
    { say: "I signed up for a marathon!", samples: ['Wow! When is it?', "That's awesome! How far can you run now?"] },
    { say: "It's in two weeks.", samples: ['Two weeks? Are you ready?', "Wow, that soon? You're crazy!"] },
    { say: "I've never run more than five miles.", samples: ['Uh-oh. Maybe walk part of it?', "Well, you've got this... I hope!"] },
  ] },
  { id: 'missed-bus', title: 'Уехавший автобус', ru: 'Друг опоздал на автобус.', turns: [
    { say: 'I missed the last bus home.', samples: ['Oh no! Where are you now?', "Seriously? Do you need a ride?"] },
    { say: "I'm at a diner. They're closing soon.", samples: ['Want me to pick you up?', "I'll grab an Uber for you."] },
    { say: 'The cook says I can help him close and he\'ll drive me.', samples: ["Ha! That's one way to get home.", 'Nice! Free food too?'] },
  ] },
  { id: 'gift', title: 'Подарок для мамы', ru: 'Друг не знает, что подарить маме.', turns: [
    { say: "My mom's birthday is tomorrow and I have nothing.", samples: ['Uh-oh. What does she like?', "Tomorrow? Let's go shopping now!"] },
    { say: 'She likes gardening and cooking.', samples: ['How about a cooking class?', 'Maybe some plants for her garden?'] },
    { say: 'Last year I got her a plant. It died in a week.', samples: ['Ha! Then a cooking class it is.', "Okay, no more plants."] },
  ] },
  { id: 'secret', title: 'Секрет соседки', ru: 'Мэгги вот-вот расскажет секрет.', turns: [
    { say: "Can you keep a secret?", samples: ['Of course! What is it?', 'Sure, my lips are sealed.'] },
    { say: "I'm moving to California... next month.", samples: ['What? No way! Why?', "Wow! I'm happy for you... but I'll miss you!"] },
    { say: "Just kidding! But you should see your face!", samples: ['Ha! You got me!', "Not funny! ...Okay, a little funny."] },
  ] },
];

if (typeof window !== 'undefined') { window.IMPROV_CARDS = IMPROV_CARDS; window.YES_AND_STORIES = YES_AND_STORIES; }
if (typeof globalThis !== 'undefined') { globalThis.IMPROV_CARDS = IMPROV_CARDS; globalThis.YES_AND_STORIES = YES_AND_STORIES; }
