/* ==========================================================================
   English Reboot — Этап 3: сквозная история «Переезд в Нью-Йорк»
   Файл: scenes_us.js — персонажи и эпизоды (данные; логика — в scenes.js).
   Партия 1: 4 эпизода — аэропорт, такси, квартира, кофейня.
   Партия 2: 8 эпизодов — офис, созвон, банк, кран, магазин, врач, вечеринка, итог месяца.
   Тексты написаны вручную на фразах из content_us.js (список phrases у эпизода
   проверяется тестом). Реплики ученика — нейтральные по роду.
   Тон вариантов выбора: natural — как сказал бы американец; formal — правильно,
   но как из учебника/анкеты; rude — грубовато. Персонаж реагирует по-разному.
   ========================================================================== */

const SCENE_CAST = {
  maggie: { name: 'Мэгги', en: 'Maggie', role: 'соседка по квартире', color: '#EC4899', initial: 'M' },
  tony: { name: 'Тони', en: 'Tony', role: 'коллега по команде', color: '#3B82F6', initial: 'T' },
  okafor: { name: 'Мистер Окафор', en: 'Mr. Okafor', role: 'арендодатель', color: '#6B7280', initial: 'O' },
  officer: { name: 'Офицер', en: 'Officer', role: 'паспортный контроль', color: '#0F766E', initial: '★' },
  ray: { name: 'Рэй', en: 'Ray', role: 'таксист', color: '#F59E0B', initial: 'R' },
  jess: { name: 'Джесс', en: 'Jess', role: 'бариста', color: '#8B5CF6', initial: 'J' },
  priya: { name: 'Прия', en: 'Priya', role: 'руководитель команды', color: '#10B981', initial: 'P' },
  garcia: { name: 'Мисс Гарсия', en: 'Ms. Garcia', role: 'сотрудница банка', color: '#0EA5E9', initial: 'G' },
  luis: { name: 'Луис', en: 'Luis', role: 'кассир в магазине', color: '#EF4444', initial: 'L' },
  kim: { name: 'Медсестра Ким', en: 'Nurse Kim', role: 'клиника без записи', color: '#14B8A6', initial: 'K' },
  sam: { name: 'Сэм', en: 'Sam', role: 'друг Мэгги', color: '#A855F7', initial: 'S' },
};

const SCENE_EPISODES = [
  /* ---------------- 1. Аэропорт JFK ---------------- */
  {
    id: 'ep1-airport', title: 'Аэропорт JFK', place: 'Нью-Йорк, паспортный контроль',
    intro: 'Самолёт приземлился в Нью-Йорке. Впереди паспортный контроль — и новая жизнь: работа, квартира, соседка Мэгги.',
    phrases: ["I'm here for business", 'How long are you staying?', 'Anything to declare?', 'I just landed', 'Text me when you land'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'officer', say: 'Next, please! Hi there. What brings you to the US?', ru: 'Следующий! Здравствуйте. С какой целью в США?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "I'm here for business. I'm starting a new job.",
            react: { say: 'Oh, nice! Congrats on the new job.', mood: 'smile' },
            coach: 'Коротко и по делу — на границе так и отвечают.', next: 'n2' },
          { tone: 'formal', text: 'Good afternoon. The purpose of my visit is professional employment.',
            react: { say: 'Uh-huh... So, work?', mood: 'confused' },
            coach: 'Грамматически верно, но звучит как анкета. Американец скажет: I\'m here for business.', next: 'n2' },
          { tone: 'rude', text: 'Work. Can we hurry up?',
            react: { say: 'Hey. Slow down. I need your passport first.', mood: 'frown' },
            coach: '«Hurry up» офицеру звучит как приказ. На границе лучше спокойно и вежливо.', next: 'n1b' },
        ] },
      },
      n1b: {
        who: 'officer', say: "Okay. Let's try again. What's the purpose of your visit?",
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Sorry, long flight. I'm here for business.",
            react: { say: 'No worries. Happens all the time.', mood: 'neutral' },
            coach: 'Извиниться и ответить — лучший выход. «Sorry, long flight» снимает напряжение.', next: 'n2' },
          { tone: 'rude', text: 'I already told you. Work.',
            react: { say: "Okay... I'm gonna need you to stay polite.", mood: 'frown' },
            coach: 'Повтор с раздражением только затягивает проверку. Вежливость тут экономит время.', next: 'n2' },
        ] },
      },
      n2: {
        who: 'officer', say: 'How long are you staying?', ru: 'На какой срок вы приехали?',
        reply: { type: 'open', prompt: 'Ответь своими словами: на какой срок приезд? (По сюжету — переезд на год, по работе.)',
          meanings: [
            { id: 'long', label: 'надолго — на год', keys: ['a year', 'one year', 'twelve months', 'for good', 'long time', 'long term', 'moving here', 'i am moving', 'relocating', 'permanently'],
              react: { say: "A year in New York! You're gonna love it.", mood: 'smile' }, next: 'n3' },
            { id: 'short', label: 'ненадолго', keys: ['a week', 'two weeks', 'few days', 'a month', 'couple of days', 'couple of weeks', 'short trip'],
              react: { say: 'Just a short trip? Your paperwork says one year.', mood: 'surprised' }, next: 'n3' },
            { id: 'unsure', label: 'пока не знаю', keys: ['not sure', 'do not know', 'no idea', 'it depends'],
              react: { say: 'You should know that. It says one year here — sound right?', mood: 'confused' }, next: 'n3' },
          ],
          samples: ["I'm here for a year.", 'About a year — I got a job here.', 'One year, on a work visa.', "I'm moving here for at least a year."],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'officer', say: 'Anything to declare?', ru: 'Есть что декларировать?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'No, nothing to declare.',
            react: { say: 'Alright.', mood: 'neutral' },
            coach: 'Идеально: «No, nothing to declare» — стандартный ответ.', next: 'n4' },
          { tone: 'formal', text: 'I hereby declare that I carry no prohibited items.',
            react: { say: 'Ha! Okay, counselor. Moving on.', mood: 'laugh' },
            coach: '«Hereby declare» — язык юристов. Офицер посмеялся, но хватило бы «No, nothing».', next: 'n4' },
          { tone: 'rude', text: 'Why would I have anything?',
            react: { say: "It's a standard question. Let's take a look at your bag.", mood: 'frown' },
            coach: 'Встречный вопрос с вызовом — и вот уже досмотр сумки. Просто «No».', next: 'n3b' },
        ] },
      },
      n3b: { who: 'officer', say: "Your bag's fine. Next time, just say no.", next: 'n4' },
      n4: { who: 'officer', say: 'Welcome to New York. Enjoy your stay!', ru: 'Добро пожаловать в Нью-Йорк!', next: 'n5' },
      n5: {
        who: 'maggie', say: "Hey, it's Maggie, your new roommate! Did your flight land?", ru: 'Привет, это Мэгги, твоя соседка! Самолёт приземлился?',
        reply: { type: 'open', prompt: 'Мэгги пишет в мессенджер. Ответь ей своими словами.',
          meanings: [
            { id: 'landed', label: 'да, на месте', keys: ['just landed', 'landed', 'i am here', 'i am at the airport', 'made it', 'in new york', 'got through customs'],
              react: { say: 'Yay! Welcome to New York!', mood: 'laugh' }, next: 'n6' },
            { id: 'not-yet', label: 'ещё нет', keys: ['not yet', 'still on the plane', 'still in line', 'not landed', 'not here yet'],
              react: { say: 'No rush! Text me when you land.', mood: 'warm' }, next: 'n6' },
          ],
          samples: ['I just landed!', 'Yep, I just landed at JFK.', 'Hey Maggie! Yes, I made it!', "I'm here! Just got through customs."],
          fallbackNext: 'n6' },
      },
      n6: { who: 'maggie', say: 'Grab a cab and text me the ETA. See you soon!', ru: 'Бери такси и напиши, когда будешь. До встречи!', end: true },
    },
  },

  /* ---------------- 2. Такси до Бруклина ---------------- */
  {
    id: 'ep2-taxi', title: 'Такси до Бруклина', place: 'Желтое такси, мост в Бруклин',
    intro: 'Очередь на такси, жёлтая машина, водитель Рэй. Нужно доехать до Бруклина, где ждёт Мэгги.',
    phrases: ['Hop in', 'Traffic is crazy', "I'm on my way", 'Keep the change', "That's a rip-off", 'Have a good one'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'ray', say: 'Hey there! Where to?', ru: 'Привет! Куда едем?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Hi! Brooklyn, please. Here's the address.",
            react: { say: 'Brooklyn, you got it. Hop in!', mood: 'smile' },
            coach: '«Hi» + адрес + «please» — так звучит нормальный пассажир.', next: 'n2' },
          { tone: 'formal', text: 'Good evening. I would like to be transported to the following address.',
            react: { say: 'Transported? Like a package? Ha! Sure, hop in.', mood: 'laugh' },
            coach: '«Transported» говорят о грузах. Просто: Brooklyn, please.', next: 'n2' },
          { tone: 'rude', text: 'Brooklyn. Go.',
            react: { say: 'Okay... nice to meet you too.', mood: 'frown' },
            coach: 'Без «hi» и «please» звучит как приказ. В американском такси принято здороваться.', next: 'n2' },
        ] },
      },
      n2: {
        who: 'ray', say: 'First time in New York?', ru: 'Первый раз в Нью-Йорке?',
        reply: { type: 'open', prompt: 'Ответь Рэю своими словами: впервые здесь или нет?',
          meanings: [
            { id: 'first', label: 'да, впервые', keys: ['first time', 'never been', 'yes', 'yeah', 'yep', 'just moved'],
              react: { say: 'Welcome! You picked a great city.', mood: 'warm' }, next: 'n3' },
            { id: 'been-before', label: 'уже бывал(а)', keys: ['been here before', 'second time', 'not my first', 'visited before', 'nope'],
              react: { say: 'Oh, so you know the drill.', mood: 'smile' }, next: 'n3' },
          ],
          samples: ["Yeah, it's my first time here!", "Yes, first time. I'm so excited.", "Nope, I've been here before.", 'First time — I just moved here.'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'ray', say: 'Traffic is crazy on the bridge. Could be forty minutes.', ru: 'На мосту жуткие пробки. Минут сорок, не меньше.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "No worries, I'm not in a rush.",
            react: { say: 'Love that attitude.', mood: 'smile' },
            coach: '«No worries» — лёгкий, очень американский ответ.', next: 'n4' },
          { tone: 'formal', text: 'That is acceptable. Please proceed at your convenience.',
            react: { say: 'Uh... okay, boss.', mood: 'confused' },
            coach: 'Звучит как письмо начальнику. В такси хватит «No worries».', next: 'n4' },
          { tone: 'rude', text: 'Ugh, seriously? Drive faster.',
            react: { say: "Hey, I'm not breaking the law for you.", mood: 'frown' },
            coach: 'Подгонять водителя невежливо — и пробку это не уберёт.', next: 'n3b' },
        ] },
      },
      n3b: { who: 'ray', say: "Relax. We'll get there.", next: 'n4' },
      n4: {
        who: 'maggie', say: 'Where are you? 😊', ru: 'Ты где? 😊',
        reply: { type: 'open', prompt: 'Мэгги пишет сообщение. Ответь, где ты и когда будешь.',
          meanings: [
            { id: 'on-way', label: 'в пути', keys: ['on my way', 'in a cab', 'in the cab', 'in a taxi', 'in the taxi', 'almost there', 'stuck in traffic', 'on the bridge', 'be there in'],
              react: { say: "Perfect! I'll make some coffee ☕", mood: 'laugh' }, next: 'n5' },
          ],
          samples: ["I'm on my way!", "I'm in a cab, stuck in traffic.", "Almost there — I'll be there in forty minutes.", 'On the bridge now. Traffic is crazy!'],
          fallbackNext: 'n5' },
      },
      n5: {
        who: 'ray', say: "Here we are! That's twenty-eight fifty.", ru: 'Приехали! С вас двадцать восемь пятьдесят.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Here's thirty. Keep the change!",
            react: { say: 'Thanks, friend! Welcome to Brooklyn!', mood: 'laugh' },
            coach: 'Оставить сдачу — нормальные чаевые в такси.', next: 'n6' },
          { tone: 'formal', text: 'Kindly accept this payment of twenty-eight dollars and fifty cents.',
            react: { say: 'Uh... thanks? Okay.', mood: 'confused' },
            coach: 'Слишком торжественно для такси. Достаточно «Here you go».', next: 'n6' },
          { tone: 'rude', text: "That's a rip-off.",
            react: { say: "Hey, that's what the meter says, pal.", mood: 'frown' },
            coach: '«Rip-off» — обвинение в обмане. Если сомневаешься, спроси: «Is that the meter price?»', next: 'n6' },
        ] },
      },
      n6: { who: 'ray', say: 'Have a good one!', ru: 'Хорошего дня!', end: true },
    },
  },

  /* ---------------- 3. Ключи от квартиры ---------------- */
  {
    id: 'ep3-apartment', title: 'Ключи от квартиры', place: 'Бруклин, квартира на третьем этаже',
    intro: 'У подъезда ждёт арендодатель, мистер Окафор: ключи, правила дома — и знакомство с Мэгги.',
    phrases: ['Nice to finally meet you', 'Make yourself at home', "I'm jet-lagged", "Let's order in", "I'll take care of it"],
    start: 'n1',
    nodes: {
      n1: {
        who: 'okafor', say: "You must be the new tenant. I'm Mr. Okafor, the landlord.", ru: 'Вы, должно быть, новый жилец. Я мистер Окафор, арендодатель.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Hi! Nice to finally meet you.',
            react: { say: 'Likewise. Come on in.', mood: 'smile' },
            coach: '«Nice to finally meet you» — если раньше общались только по почте.', next: 'n2' },
          { tone: 'formal', text: 'Greetings, Mr. Okafor. It is an honor to make your acquaintance.',
            react: { say: "An honor? Ha. It's just an apartment, but thank you.", mood: 'surprised' },
            coach: '«Honor» и «acquaintance» — для приёма у посла. Хватит «Nice to meet you».', next: 'n2' },
          { tone: 'rude', text: 'Yeah, yeah. Where are the keys?',
            react: { say: 'Patience. First, a few house rules.', mood: 'frown' },
            coach: 'С арендодателем лучше начать с приветствия — вам ещё год жить рядом.', next: 'n1b' },
        ] },
      },
      n1b: { who: 'okafor', say: 'Rule number one: be polite to your landlord.', next: 'n2' },
      n2: {
        who: 'okafor', say: 'Rent is due on the first of every month. Any questions?', ru: 'Аренда — первого числа каждого месяца. Вопросы есть?',
        reply: { type: 'open', prompt: 'Задай арендодателю вопрос своими словами — про Wi-Fi, стирку или мусор. Или скажи, что вопросов нет.',
          meanings: [
            { id: 'wifi', label: 'вопрос про Wi-Fi', keys: ['wi-fi', 'wifi', 'internet', 'password'],
              react: { say: "The Wi-Fi password is on the fridge.", mood: 'neutral' }, next: 'n3' },
            { id: 'laundry', label: 'вопрос про стирку', keys: ['laundry', 'washing machine', 'washer', 'dryer'],
              react: { say: 'Laundry room is in the basement.', mood: 'smile' }, next: 'n3' },
            { id: 'trash', label: 'вопрос про мусор', keys: ['trash', 'garbage', 'recycling'],
              react: { say: 'Trash goes out on Tuesdays.', mood: 'smile' }, next: 'n3' },
            { id: 'none', label: 'вопросов нет', keys: ['no questions', 'all good', 'i am good', 'no thanks', 'nope', 'that is all'],
              react: { say: 'Great. Here are your keys.', mood: 'smile' }, next: 'n3' },
          ],
          samples: ["Where's the laundry room?", "What's the Wi-Fi password?", 'When do I take out the trash?', 'No questions — all good, thanks!'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'maggie', say: "Hey, roomie! I'm Maggie. Welcome home!", ru: 'Привет, сосед! Я Мэгги. Добро пожаловать домой!',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Hey, Maggie! So good to meet you in person.',
            react: { say: 'Come here, hug!', mood: 'laugh' },
            coach: 'Тепло и просто — с соседкой именно так.', next: 'n4' },
          { tone: 'formal', text: 'Hello, Maggie. I am pleased to meet you.',
            react: { say: "Wow, so formal! Relax, we're roommates now 😄", mood: 'surprised' },
            coach: '«Pleased to meet you» для соседки звучит холодно — как на собеседовании.', next: 'n4' },
          { tone: 'rude', text: 'Hi. Which room is mine?',
            react: { say: "Uh... okay. It's the one on the left.", mood: 'confused' },
            coach: 'Сразу к делу — и первое впечатление подпорчено. Начни с «Nice to meet you».', next: 'n4' },
        ] },
      },
      n4: {
        who: 'maggie', say: 'Make yourself at home. Do you need anything?', ru: 'Располагайся. Тебе что-нибудь нужно?',
        reply: { type: 'open', prompt: 'Ответь Мэгги своими словами: что тебе сейчас нужно (или ничего)?',
          meanings: [
            { id: 'tired', label: 'устал(а), нужен отдых', keys: ['tired', 'jet lag', 'jet lagged', 'sleep', 'nap', 'exhausted', 'rest', 'shower'],
              react: { say: "Totally get it. Take a nap, we'll talk later.", mood: 'warm' }, next: 'n5' },
            { id: 'hungry', label: 'голоден/голодна', keys: ['hungry', 'starving', 'food', 'eat', 'dinner', 'snack', 'order in'],
              react: { say: "Same! Let's order in.", mood: 'laugh' }, next: 'n5' },
            { id: 'nothing', label: 'ничего не нужно', keys: ['i am good', 'i am fine', 'all good', 'nothing', 'no thanks', 'not right now'],
              react: { say: "Cool. I'm here if you need me.", mood: 'smile' }, next: 'n5' },
          ],
          samples: ["I'm good, thanks!", "Honestly, I'm jet-lagged. I need a nap.", "I'm starving. Wanna order in?", 'Just a shower and some sleep.'],
          fallbackNext: 'n5' },
      },
      n5: {
        who: 'maggie', say: "Oh, one more thing: it's your turn to take out the trash on Tuesday 😄", ru: 'Да, и ещё: во вторник твоя очередь выносить мусор 😄',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Ha, deal. I'll take care of it.",
            react: { say: 'I like you already.', mood: 'laugh' },
            coach: '«Deal» + «I\'ll take care of it» — легко и надёжно.', next: 'n6' },
          { tone: 'formal', text: 'I acknowledge my responsibility regarding the trash.',
            react: { say: "You're funny. Okay, robot.", mood: 'laugh' },
            coach: 'Так пишут в договорах, а не говорят на кухне.', next: 'n6' },
          { tone: 'rude', text: 'Seriously? I just got here.',
            react: { say: "Kidding! ...Kind of.", mood: 'confused' },
            coach: 'Мэгги шутила, а ответ получился колючим. Подыграть было бы проще.', next: 'n6' },
        ] },
      },
      n6: { who: 'maggie', say: 'Welcome home, roomie!', ru: 'С новосельем, сосед!', end: true },
    },
  },

  /* ---------------- 4. Кофейня за углом ---------------- */
  {
    id: 'ep4-coffee', title: 'Кофейня за углом', place: 'Бруклин, утро перед первым рабочим днём',
    intro: 'Утро. Кофейня за углом, бариста Джесс — и неожиданная встреча с будущим коллегой.',
    phrases: ['Can I get a coffee?', 'What do you recommend?', 'For here or to go?', 'Are you in line?', 'What do you do?', 'Sounds like a plan'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'jess', say: 'Morning! What can I get you?', ru: 'Доброе утро! Что вам приготовить?',
        reply: { type: 'open', prompt: 'Закажи что-нибудь своими словами — или спроси, что посоветуют.',
          meanings: [
            { id: 'order', label: 'заказ', keys: ['coffee', 'latte', 'cappuccino', 'americano', 'espresso', 'cold brew', 'tea', 'can i get', 'i will have', 'i will get'],
              react: { say: 'Great choice!', mood: 'smile' }, next: 'n2' },
            { id: 'recommend', label: 'просьба посоветовать', keys: ['what do you recommend', 'recommend', 'what is good', 'what is popular'],
              react: { say: 'Our oat latte is kind of famous around here. Want one?', mood: 'laugh' }, next: 'n2' },
          ],
          samples: ['Can I get a coffee?', 'Can I get a large iced latte with oat milk?', 'What do you recommend?', 'Just a black coffee, please.'],
          fallbackNext: 'n2' },
      },
      n2: {
        who: 'jess', say: 'For here or to go?', ru: 'Здесь или с собой?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'To go, please.',
            react: { say: 'Coming right up!', mood: 'smile' },
            coach: 'Ровно так и отвечают: «To go» или «For here».', next: 'n3' },
          { tone: 'formal', text: 'I would prefer to consume it outside of this establishment.',
            react: { say: 'Ha! So... to go?', mood: 'laugh' },
            coach: '«Consume» и «establishment» — язык инструкций. В кофейне: «To go, please».', next: 'n3' },
          { tone: 'rude', text: 'Whatever. Just make it.',
            react: { say: '...Okay. One coffee.', mood: 'frown' },
            coach: 'Бариста не виновата, что утро. Одно «please» меняет всё.', next: 'n3' },
        ] },
      },
      n3: {
        who: 'tony', say: 'Hey — sorry, are you in line?', ru: 'Привет — извини, ты в очереди?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'No, go ahead!',
            react: { say: 'Thanks! Hey, wait... are you the new hire at Brightline?', mood: 'surprised' },
            coach: '«Go ahead» — «проходи», самый естественный ответ.', next: 'n4' },
          { tone: 'formal', text: 'Negative. You may proceed.',
            react: { say: 'Ha! Okay, captain. Hey... are you the new hire at Brightline?', mood: 'laugh' },
            coach: '«Negative, proceed» — рация военных. Просто: «No, go ahead».', next: 'n4' },
          { tone: 'rude', text: 'Yes. Back off.',
            react: { say: 'Whoa, okay. Sorry!', mood: 'frown' },
            coach: '«Back off» — «отвали». Слишком резко для очереди за кофе.', next: 'n3b' },
        ] },
      },
      n3b: { who: 'tony', say: 'No rush. Hey... are you the new hire at Brightline?', next: 'n4' },
      n4: {
        who: 'tony', say: "I'm Tony, I'm on your team! So, what do you do?", ru: 'Я Тони, мы в одной команде! А ты чем занимаешься?',
        reply: { type: 'open', prompt: 'Расскажи Тони своими словами, кем работаешь.',
          meanings: [
            { id: 'job', label: 'рассказ о работе', keys: ['i am in', 'i work in', 'i work as', 'i am a', 'i am an', 'developer', 'designer', 'marketing', 'sales', 'engineer', 'manager', 'analyst', 'i do'],
              react: { say: "Awesome, we're gonna work together a lot.", mood: 'laugh' }, next: 'n5' },
          ],
          samples: ["I'm in sales.", "I'm a designer — I'm on your team!", 'I work in marketing.', "I'm the new developer. I start Monday."],
          fallbackNext: 'n5' },
      },
      n5: {
        who: 'tony', say: "Wanna grab lunch on Monday? I'll show you around.", ru: 'Пообедаем в понедельник? Покажу тебе всё вокруг.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "I'm down! Sounds like a plan.",
            react: { say: 'Sweet! See you Monday.', mood: 'laugh' },
            coach: '«I\'m down» + «Sounds like a plan» — живое американское «давай!».', next: 'n6' },
          { tone: 'formal', text: 'I would be delighted to accept your kind invitation.',
            react: { say: 'Ha, okay, fancy! See you Monday.', mood: 'surprised' },
            coach: 'Так отвечают на приглашение на свадьбу. Коллеге: «Sounds good!»', next: 'n6' },
          { tone: 'rude', text: "Maybe. I don't even know you.",
            react: { say: 'Fair enough... The offer stands!', mood: 'confused' },
            coach: 'Честно, но холодно. В новой команде такие приглашения — лучший шанс подружиться.', next: 'n6' },
        ] },
      },
      n6: { who: 'jess', say: 'One coffee to go! Have a great first day!', ru: 'Кофе с собой! Удачного первого дня!', end: true },
    },
  },
  /* ---------------- 5. Первый рабочий день ---------------- */
  {
    id: 'ep5-office', title: 'Первый рабочий день', place: 'Офис Brightline, Манхэттен',
    intro: 'Понедельник. Первый день в Brightline: Тони обещал показать офис, а руководитель команды Прия хочет познакомиться.',
    phrases: ['Tell me about yourself', "What's the deadline?", "It's due Friday", 'Can you walk me through it?', "I'm swamped", 'Can you cover for me?', "I'll take care of it", "Let's call it a day"],
    start: 'n1',
    nodes: {
      n1: {
        who: 'tony', say: 'Hey, you made it! Welcome to Brightline. How was the commute?', ru: 'Привет, ты на месте! Добро пожаловать в Brightline. Как дорога?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Not bad! The subway was packed, though.',
            react: { say: 'Ha, welcome to New York. It\'s always packed.', mood: 'laugh' },
            coach: '«Not bad» + маленькая деталь — идеальный small talk. «Though» в конце — «правда, зато».', next: 'n2' },
          { tone: 'formal', text: 'The commute was satisfactory. Thank you for asking.',
            react: { say: 'Satisfactory... okay! Glad you\'re here.', mood: 'confused' },
            coach: '«Satisfactory» — слово из отчёта. Коллеге: «Not bad!» или «Pretty easy».', next: 'n2' },
          { tone: 'rude', text: 'Terrible. I already hate this city.',
            react: { say: 'Oof. Rough morning, huh?', mood: 'frown' },
            coach: 'Жаловаться можно, но «hate this city» в первый же день звучит мрачно. Мягче: «Kind of rough, honestly».', next: 'n1b' },
        ] },
      },
      n1b: { who: 'tony', say: 'It gets better, I promise. Coffee helps. Come on, meet the team.', ru: 'Дальше будет лучше, обещаю. Кофе помогает. Пойдём, познакомлю с командой.', next: 'n2' },
      n2: {
        who: 'priya', say: "Hi, I'm Priya — I lead the team. So, tell me about yourself!", ru: 'Привет, я Прия, руковожу командой. Расскажи о себе!',
        reply: { type: 'open', prompt: 'Расскажи о себе в паре фраз: откуда ты, какой у тебя опыт или что любишь.',
          meanings: [
            { id: 'background', label: 'рассказ о себе', keys: ['i am from', 'i grew up', 'i worked', 'i have been', 'before this', 'i used to', 'years', 'my background', 'i moved', 'moved here'],
              react: { say: 'Oh, cool! Nice to have you on the team.', mood: 'warm' }, next: 'n3' },
            { id: 'hobby', label: 'увлечения', keys: ['i like', 'i love', 'i am into', 'in my free time', 'i enjoy', 'my hobby'],
              react: { say: 'Nice! We should do a team thing around that sometime.', mood: 'smile' }, next: 'n3' },
          ],
          samples: ["I'm from Kazan. I worked in marketing for five years.", 'I just moved here for this job.', "In my free time, I'm into hiking and photography.", 'I used to work at a startup, so I love fast projects.'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'priya', say: "Today's pretty chill. Any questions so far?", ru: 'Сегодня спокойный день. Есть вопросы?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Yeah — what's the deadline for my first task?",
            react: { say: "No rush — it's due Friday.", mood: 'smile' },
            coach: 'Короткий прямой вопрос — то, что нужно. «What\'s the deadline?» спрашивают постоянно.', next: 'n4' },
          { tone: 'formal', text: 'I would like to inquire about the deadline of my first assignment.',
            react: { say: "Sure! It's due Friday. And you can relax — we're pretty casual here.", mood: 'laugh' },
            coach: '«Inquire» и «assignment» — как в официальном письме. Вслух: «What\'s the deadline?»', next: 'n4' },
          { tone: 'rude', text: "Nope. I'll figure it out myself.",
            react: { say: 'Okay... but seriously, don\'t be shy to ask.', mood: 'confused' },
            coach: 'Самостоятельность — хорошо, но «nope» руководителю звучит как «отстань». Мягче: «Not yet, thanks!»', next: 'n3b' },
        ] },
      },
      n3b: { who: 'priya', say: "Your first task is due Friday, by the way. Tony will show you around.", ru: 'Кстати, первая задача — к пятнице. Тони всё покажет.', next: 'n4' },
      n4: {
        who: 'tony', say: "Okay, so this is our project board. Kind of confusing, right?", ru: 'Так, вот наша доска проектов. Запутанно, да?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'A little. Can you walk me through it?',
            react: { say: "Sure! It's easier than it looks.", mood: 'smile' },
            coach: '«Walk me through it» — «покажи по шагам». Очень американское и очень полезное.', next: 'n5' },
          { tone: 'formal', text: 'Could you kindly provide a detailed explanation of this system?',
            react: { say: 'A detailed explanation... okay, professor! Let me walk you through it.', mood: 'laugh' },
            coach: 'Слишком торжественно для коллеги за соседним столом. Проще: «Can you walk me through it?»', next: 'n5' },
          { tone: 'rude', text: "Yeah, it's a total mess.",
            react: { say: "Ha — fair. It kind of is. Here's how it works.", mood: 'confused' },
            coach: 'Честно, но в первый день лучше не критиковать чужую работу. Нейтрально: «It\'s a lot!»', next: 'n5' },
        ] },
      },
      n5: {
        who: 'tony', say: "Hey, quick favor. I'm swamped today — can you cover for me at the three o'clock meeting? Just take notes.", ru: 'Слушай, небольшая просьба. Я завален делами — подменишь меня на встрече в три? Просто записать главное.',
        reply: { type: 'open', prompt: 'Ответь Тони: согласись, уточни или вежливо откажись.',
          meanings: [
            { id: 'agree', label: 'согласие', keys: ['sure', 'no problem', 'i will take care of it', 'i got you', 'of course', 'happy to', 'yes', 'i can do that'],
              react: { say: "You're the best! I owe you one.", mood: 'laugh' }, next: 'n6' },
            { id: 'unsure', label: 'уточнение', keys: ['let me check', 'not sure', 'what do i need', 'what should i', 'which meeting'],
              react: { say: "Just write down the action items. That's it, easy!", mood: 'smile' }, next: 'n6' },
            { id: 'refuse', label: 'вежливый отказ', keys: ['can not', 'i am busy', 'i have a call', 'maybe next time', 'i will pass', 'of course not', 'no way'],
              react: { say: "No worries! I'll ask someone else.", mood: 'neutral' }, next: 'n6' },
          ],
          samples: ["Sure, I'll take care of it.", 'No problem, I got you.', 'Let me check my calendar first.', "Sorry, I can't — I have a call at three."],
          fallbackNext: 'n6' },
      },
      n6: { who: 'priya', say: "Great first day, everyone. Let's call it a day — see you tomorrow!", ru: 'Отличный первый день. На сегодня всё — до завтра!', end: true },
    },
  },

  /* ---------------- 6. Первый созвон ---------------- */
  {
    id: 'ep6-call', title: 'Первый созвон', place: 'Zoom, еженедельная встреча команды',
    intro: 'Вторник, утренний созвон команды. Микрофон, связь, новости по задачам — и спорное решение, с которым хочется не согласиться.',
    phrases: ['Can you hear me?', "You're on mute", 'Sorry, I was on mute', 'Quick update', 'Can I jump in here?', "I see where you're coming from", "That's fair", "Let's put a pin in it", "You're breaking up", 'Could you say that again?', 'Let me rephrase that', "Let's wrap up", "I'll send a recap", 'Thanks for your time'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'priya', say: 'Hi everyone! Can you hear me?', ru: 'Всем привет! Меня слышно?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Yep, loud and clear!',
            react: { say: 'Perfect. Let\'s get started.', mood: 'smile' },
            coach: '«Loud and clear» — «слышно отлично». Стандартный ответ на созвоне.', next: 'n2' },
          { tone: 'formal', text: 'Affirmative. The audio quality is acceptable.',
            react: { say: 'Ha, thanks, mission control. Let\'s get started.', mood: 'laugh' },
            coach: '«Affirmative» — как по рации у военных. Достаточно: «Yes, I can hear you».', next: 'n2' },
          { tone: 'rude', text: 'Yeah, obviously.',
            react: { say: 'Okay... great. Let\'s get started.', mood: 'neutral' },
            coach: '«Obviously» звучит как «что за глупый вопрос». На созвоне его задают всегда — отвечай легко.', next: 'n2' },
        ] },
      },
      n2: {
        who: 'tony', say: "Hey, I think you're on mute!", ru: 'Эй, кажется, у тебя выключен микрофон!',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Sorry, I was on mute! Can you hear me now?',
            react: { say: 'Yep, we got you now.', mood: 'smile' },
            coach: 'Так говорят по сто раз в день. «Sorry, I was on mute» — фраза-спасатель любого созвона.', next: 'n3' },
          { tone: 'formal', text: 'My apologies. My microphone appears to have been disabled.',
            react: { say: 'All good! We can hear you now.', mood: 'laugh' },
            coach: 'Длинно и официально. Коротко: «Sorry, I was on mute!»', next: 'n3' },
          { tone: 'rude', text: "No, I'm not.",
            react: { say: 'Uh... you kind of were.', mood: 'confused' },
            coach: 'Спорить, когда тебя правда не слышно, — неловко. Проще извиниться и продолжить.', next: 'n2b' },
        ] },
      },
      n2b: { who: 'tony', say: "Anyway, we can hear you now. No worries!", ru: 'В общем, теперь слышно. Всё нормально!', next: 'n3' },
      n3: {
        who: 'priya', say: "Let's do a quick update from everyone. What are you working on?", ru: 'Давайте коротко по кругу. Над чем ты сейчас работаешь?',
        reply: { type: 'open', prompt: 'Коротко расскажи, над чем работаешь — или попроси помощи.',
          meanings: [
            { id: 'progress', label: 'рассказ о задаче', keys: ['i am working on', 'i am looking into', 'i finished', 'i started', 'almost done', 'i am still', 'i am setting up'],
              react: { say: 'Got it, thanks for the update!', mood: 'smile' }, next: 'n4' },
            { id: 'help', label: 'просьба о помощи', keys: ['i need a hand', 'i am stuck', 'walk me through', 'could use some help', 'i have a question'],
              react: { say: 'Totally fine — Tony, can you help after the call?', mood: 'smile' }, next: 'n4' },
          ],
          samples: ["I'm working on the onboarding guide. Almost done!", "I'm still setting up my laptop, honestly.", "I'm stuck on the new dashboard. I need a hand with it.", 'I started the first task yesterday.'],
          fallbackNext: 'n4' },
      },
      n4: {
        who: 'priya', say: "So, to hit the launch date, we'll skip user testing this time.", ru: 'Чтобы успеть к запуску, в этот раз пропустим тестирование с пользователями.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Can I jump in here? I see where you're coming from, but testing could save us time later.",
            react: { say: "That's fair. Let's put a pin in it and talk after the call.", mood: 'warm' },
            coach: 'Сначала признать чужую логику («I see where you\'re coming from»), потом свой довод — так спорят на работе в США.', next: 'n5' },
          { tone: 'formal', text: 'I must object. Skipping testing is completely unacceptable.',
            react: { say: "Wow, okay. Strong opinion! Let's put a pin in it.", mood: 'surprised' },
            coach: '«I must object» и «unacceptable» звучат как в суде. Мягкое несогласие работает лучше.', next: 'n5' },
          { tone: 'rude', text: 'That makes no sense.',
            react: { say: "Hmm. Let's keep it respectful, please.", mood: 'frown' },
            coach: 'Резкое «makes no sense» на общем созвоне задевает. Лучше: «I\'m not sure about that — can I explain why?»', next: 'n4b' },
        ] },
      },
      n4b: { who: 'priya', say: "But point taken. Let's put a pin in it and talk later.", ru: 'Но мысль поняла. Отложим и обсудим позже.', next: 'n5' },
      n5: {
        who: 'tony', say: "Sorry, you're breaking up... Could you say that again?", ru: 'Извини, связь прерывается… Можешь повторить?',
        reply: { type: 'open', prompt: 'Связь пропала. Повтори мысль другими словами или предложи написать в чат.',
          meanings: [
            { id: 'repeat', label: 'повтор мысли', keys: ['let me rephrase', 'what i mean is', 'i said', 'i was saying', 'basically'],
              react: { say: 'Got it now, thanks!', mood: 'smile' }, next: 'n6' },
            { id: 'chat', label: 'предложение написать', keys: ['in the chat', 'i will type', 'i will write', 'i will send', 'recap'],
              react: { say: 'Perfect, the chat works.', mood: 'smile' }, next: 'n6' },
          ],
          samples: ['Let me rephrase that. Testing could save us time later.', 'Basically, I think we need user testing.', "I'll type it in the chat.", "My internet is acting up — I'll write it in the chat."],
          fallbackNext: 'n6' },
      },
      n6: { who: 'priya', say: "Okay, let's wrap up. I'll send a recap. Thanks for your time, everyone!", ru: 'Ладно, закругляемся. Пришлю итоги. Всем спасибо за время!', end: true },
    },
  },
  /* ---------------- 7. Счёт в банке ---------------- */
  {
    id: 'ep7-bank', title: 'Счёт в банке', place: 'Отделение банка на Флэтбуш-авеню',
    intro: 'Первая зарплата скоро придёт — пора открыть американский счёт. Операционистка мисс Гарсия готова помочь.',
    phrases: ["I'd like to open an account", 'I need to deposit a check', "There's a fee", "That's a rip-off", "What's the interest rate?"],
    start: 'n1',
    nodes: {
      n1: {
        who: 'garcia', say: 'Hi, welcome to First City Bank! How can I help you today?', ru: 'Здравствуйте, добро пожаловать в First City Bank! Чем могу помочь?',
        reply: { type: 'open', prompt: 'Скажи, зачем ты в банке: открыть счёт или внести чек.',
          meanings: [
            { id: 'account', label: 'открыть счёт', keys: ['open an account', 'new account', 'checking account', 'savings account', 'bank account'],
              react: { say: "Sure! Let's get you set up.", mood: 'smile' }, next: 'n2' },
            { id: 'deposit', label: 'внести чек', keys: ['deposit a check', 'deposit', 'cash a check', 'my paycheck'],
              react: { say: "Of course! First, let's open an account for you.", mood: 'smile' }, next: 'n2' },
          ],
          samples: ["I'd like to open an account.", 'Hi! I need to open a checking account.', 'I need to deposit a check — my first paycheck!', 'I just moved here, so I need a bank account.'],
          fallbackNext: 'n2' },
      },
      n2: {
        who: 'garcia', say: 'Do you have a photo ID and proof of address?', ru: 'У вас есть документ с фото и подтверждение адреса?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Yep, here's my passport and my lease.",
            react: { say: 'Perfect, that works.', mood: 'smile' },
            coach: '«Here\'s my…» — «вот мой…». Протягиваешь документ и называешь его — так и делают.', next: 'n3' },
          { tone: 'formal', text: 'I am in possession of the required identification documents.',
            react: { say: "Great... so, can I see them?", mood: 'confused' },
            coach: '«In possession of» — язык протокола. Проще: «Yes, here you go».', next: 'n3' },
          { tone: 'rude', text: 'Why do you need all that?',
            react: { say: "It's the law, sorry. Just a quick check.", mood: 'frown' },
            coach: 'Вопрос нормальный, но тон подозрительный. Мягче: «Sure — just curious, why do you need it?»', next: 'n2b' },
        ] },
      },
      n2b: { who: 'garcia', say: 'Every bank in the US asks for it. Thanks for understanding!', ru: 'Это спрашивает любой банк в США. Спасибо за понимание!', next: 'n3' },
      n3: {
        who: 'garcia', say: 'Great. Just so you know, this checking account has a twelve-dollar monthly fee.', ru: 'Отлично. Чтобы вы знали: у этого счёта ежемесячная комиссия — двенадцать долларов.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Oh, there's a fee? Is there any way to waive it?",
            react: { say: "Yes! It's free if you set up direct deposit from your job.", mood: 'warm' },
            coach: '«Waive the fee» — «отменить комиссию». В американском банке это можно и нужно спрашивать.', next: 'n4' },
          { tone: 'formal', text: 'I consider this fee to be unreasonable.',
            react: { say: 'I understand. It goes away with direct deposit, though.', mood: 'neutral' },
            coach: 'Звучит как жалоба в письменном виде. Вслух проще: «Is there any way to avoid the fee?»', next: 'n4' },
          { tone: 'rude', text: "Twelve bucks a month? That's a rip-off.",
            react: { say: 'I hear you.', mood: 'frown' },
            coach: '«Rip-off» — «грабёж». Сказать можно, но операционистка цены не назначает. Лучше спросить, как её избежать.', next: 'n3b' },
        ] },
      },
      n3b: { who: 'garcia', say: "Good news, though: it's free with direct deposit from your job.", ru: 'Но есть хорошая новость: с зарплатой на этот счёт комиссии нет.', next: 'n4' },
      n4: {
        who: 'garcia', say: "I'll also open a savings account for you. Any questions?", ru: 'Ещё открою вам сберегательный счёт. Есть вопросы?',
        reply: { type: 'open', prompt: 'Задай вопрос: про процент, про карту или про приложение банка.',
          meanings: [
            { id: 'rate', label: 'вопрос про процент', keys: ['interest rate', 'interest', 'how much do i earn'],
              react: { say: 'Four percent a year on savings.', mood: 'smile' }, next: 'n5' },
            { id: 'card', label: 'вопрос про карту', keys: ['debit card', 'my card', 'the card', 'credit card'],
              react: { say: "Your debit card comes in the mail in about a week.", mood: 'smile' }, next: 'n5' },
            { id: 'app', label: 'вопрос про приложение', keys: ['app', 'online banking', 'apple pay', 'on my phone'],
              react: { say: 'Yep — just download our app and log in.', mood: 'smile' }, next: 'n5' },
          ],
          samples: ["What's the interest rate?", 'When will I get my debit card?', 'Do you have an app for online banking?', 'Can I use the card with Apple Pay?'],
          fallbackNext: 'n5' },
      },
      n5: { who: 'garcia', say: "You're all set! Welcome to First City Bank.", ru: 'Всё готово! Добро пожаловать в First City Bank.', end: true },
    },
  },

  /* ---------------- 8. Засор на кухне ---------------- */
  {
    id: 'ep8-sink', title: 'Засор на кухне', place: 'Бруклин, квартира на третьем этаже',
    intro: 'Вечер, раковина снова засорилась, а у Мэгги сел телефон. Звонить мистеру Окафору придётся тебе.',
    phrases: ['The sink is clogged', 'My phone died', "Who's calling?", "I'll call the plumber", "It's a bad connection", 'Can you speak up?', "Pizza's on me"],
    start: 'n1',
    nodes: {
      n1: {
        who: 'maggie', say: 'Ugh, the sink is clogged again! And my phone died. Can you call Mr. Okafor?', ru: 'Ну вот, раковина опять засорилась! А у меня сел телефон. Позвонишь мистеру Окафору?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Sure, I'll call him right now.",
            react: { say: 'Thank you! You\'re a lifesaver.', mood: 'warm' },
            coach: 'Коротко и по-соседски. «Right now» — «прямо сейчас».', next: 'n2' },
          { tone: 'formal', text: 'Certainly. I shall contact the landlord immediately.',
            react: { say: '"Shall"? Okay, Your Majesty. Thanks!', mood: 'laugh' },
            coach: '«Shall» в США звучит торжественно, почти по-королевски. Проще: «Sure, I\'ll call him».', next: 'n2' },
          { tone: 'rude', text: "Why me? It's your mess.",
            react: { say: 'Wow. Okay...', mood: 'frown' },
            coach: 'Соседи делят и хорошее, и засоры. Если не хочется — скажи мягче: «Can it wait till your phone charges?»', next: 'n1b' },
        ] },
      },
      n1b: { who: 'maggie', say: "Fine, sorry. I'll do the dishes all week — please call him?", ru: 'Ладно, прости. Всю неделю мою посуду — позвони ему, пожалуйста?', next: 'n2' },
      n2: {
        who: 'okafor', say: "Hello? Who's calling?", ru: 'Алло? Кто это?',
        reply: { type: 'open', prompt: 'Представься по телефону — или сразу скажи, в чём проблема.',
          meanings: [
            { id: 'intro', label: 'представление', keys: ['this is', 'it is', 'your tenant', 'new tenant', 'roommate', 'apartment'],
              react: { say: "Oh, hello! How's the apartment treating you?", mood: 'smile' }, next: 'n3' },
            { id: 'problem', label: 'сразу о проблеме', keys: ['sink is clogged', 'clogged', 'sink', 'leaking', 'problem'],
              react: { say: 'Oh no, not again!', mood: 'surprised' }, next: 'n4' },
          ],
          samples: ["Hi, Mr. Okafor! This is Maggie's new roommate.", "Hi, it's your new tenant from apartment 3B.", 'Hi! The sink is clogged in our kitchen.', 'Hello, we have a problem with the kitchen sink.'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'okafor', say: "Good, good. So, what's going on?", ru: 'Хорошо, хорошо. Так что случилось?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'The sink is clogged again. Could you send someone?',
            react: { say: "Of course. I'll call the plumber.", mood: 'smile' },
            coach: 'Проблема + просьба в одном звонке — идеально. «Could you send someone?» — вежливо и ясно.', next: 'n4' },
          { tone: 'formal', text: 'I regret to inform you that there is a blockage in the sink.',
            react: { say: "A blockage... got it. I'll call the plumber.", mood: 'confused' },
            coach: '«I regret to inform you» — так сообщают плохие новости в письмах. Проще: «The sink is clogged».', next: 'n4' },
          { tone: 'rude', text: 'Your sink is broken again. Fix it.',
            react: { say: "...I'll call the plumber. A \"please\" would be nice.", mood: 'frown' },
            coach: 'По сути всё верно, но приказ хозяину квартиры портит отношения. Добавь «Could you…?»', next: 'n4' },
        ] },
      },
      n4: {
        who: 'okafor', say: "Sorry, it's a bad connection — can you speak up? When are you home?", ru: 'Извини, плохо слышно — можешь погромче? Когда ты будешь дома?',
        reply: { type: 'open', prompt: 'Скажи погромче, когда ты дома, чтобы пришёл сантехник.',
          meanings: [
            { id: 'time', label: 'время', keys: ['i am home', 'after', 'tomorrow', 'tonight', 'morning', 'afternoon', 'evening', 'anytime', 'any time', 'all day'],
              react: { say: "Perfect. He'll be there. Thanks for letting me know!", mood: 'smile' }, next: 'n5' },
          ],
          samples: ["I'm home after six.", 'Tomorrow morning works for me.', "I'm free all day Saturday.", 'Anytime after five is fine.'],
          fallbackNext: 'n5' },
      },
      n5: { who: 'maggie', say: "You handled that like a pro. Pizza's on me tonight!", ru: 'Справились как профи. Пицца сегодня за мой счёт!', end: true },
    },
  },

  /* ---------------- 9. Магазин у дома ---------------- */
  {
    id: 'ep9-store', title: 'Магазин у дома', place: 'Магазин и аптека на углу',
    intro: 'Молоко закончилось, телефон опять садится. Магазин на углу работает до полуночи, на кассе — Луис.',
    phrases: ["I'm just browsing", 'Where can I find the milk?', 'Do you sell phone chargers?', 'Next in line', 'Cash or card?', 'My card was declined', 'Do you accept Apple Pay?', "I'm all set", 'Have a nice day'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'luis', say: 'Hey there! Can I help you find anything?', ru: 'Привет! Помочь что-нибудь найти?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "I'm good, thanks — I'm just browsing.",
            react: { say: 'Sure thing! Let me know if you need anything.', mood: 'smile' },
            coach: '«I\'m just browsing» — «я просто смотрю». Вежливо и без лишних слов.', next: 'n2' },
          { tone: 'formal', text: 'No, thank you. I am merely examining the merchandise.',
            react: { say: 'Ha, "examining the merchandise." Got it!', mood: 'laugh' },
            coach: '«Merchandise» и «merely» — для каталогов. В магазине: «Just looking, thanks».', next: 'n2' },
          { tone: 'rude', text: 'No. Leave me alone.',
            react: { say: "Okay... I'll be at the register.", mood: 'frown' },
            coach: 'Продавец просто вежлив. «No, thanks, I\'m good» отказывает так же, но без обиды.', next: 'n1b' },
        ] },
      },
      n1b: { who: 'luis', say: 'Just holler if you need me.', ru: 'Если что — зови.', next: 'n2' },
      n2: {
        who: 'luis', say: 'Our store is kind of a maze, by the way. Just ask!', ru: 'Кстати, у нас тут лабиринт. Спрашивай!',
        reply: { type: 'open', prompt: 'Спроси, где найти молоко, или есть ли зарядки для телефона.',
          meanings: [
            { id: 'find', label: 'вопрос, где найти', keys: ['where can i find', 'where is', 'where are', 'do you sell', 'do you have'],
              react: { say: 'Aisle five, on the left!', mood: 'smile' }, next: 'n3' },
          ],
          samples: ['Where can I find the milk?', 'Do you sell phone chargers?', 'Where are the eggs?', 'Do you have oat milk?'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'luis', say: 'Next in line! Cash or card?', ru: 'Следующий! Наличные или карта?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Card, please.',
            react: { say: 'Go ahead and tap.', mood: 'smile' },
            coach: 'На «Cash or card?» хватает одного слова и «please».', next: 'n4' },
          { tone: 'formal', text: 'I will be remitting payment by debit card.',
            react: { say: 'Remitting... okay! Tap whenever you\'re ready.', mood: 'confused' },
            coach: '«Remit payment» пишут в счетах. На кассе: «Card, please».', next: 'n4' },
          { tone: 'rude', text: 'Card, obviously. Who even uses cash?',
            react: { say: 'Lots of people, actually. Go ahead.', mood: 'neutral' },
            coach: '«Obviously» звучит свысока. Кассир спрашивает это у всех — отвечай просто.', next: 'n4' },
        ] },
      },
      n4: {
        who: 'luis', say: 'Hmm, it says your card was declined. Wanna try again?', ru: 'Хм, карта отклонена. Попробуешь ещё раз?',
        reply: { type: 'open', prompt: 'Не паникуй: попроси попробовать ещё раз, предложи другой способ оплаты или скажи, что проверишь баланс.',
          meanings: [
            { id: 'retry', label: 'попробовать ещё раз', keys: ['try again', 'one more time', 'let me try'],
              react: { say: 'Sure. ...Okay, it went through!', mood: 'smile' }, next: 'n5' },
            { id: 'other', label: 'другой способ оплаты', keys: ['another card', 'different card', 'apple pay', 'cash', 'my phone'],
              react: { say: 'Yep, we take that. ...All good!', mood: 'smile' }, next: 'n5' },
            { id: 'check', label: 'проверить баланс', keys: ['let me check', 'my balance', 'call my bank', 'my bank'],
              react: { say: 'Take your time. Oh — it went through on the second try!', mood: 'smile' }, next: 'n5' },
          ],
          samples: ['My card was declined? Can I try again?', 'Let me use another card.', 'Do you accept Apple Pay?', 'Weird. Let me check my balance.'],
          fallbackNext: 'n5' },
      },
      n5: {
        who: 'luis', say: 'Do you need a bag?', ru: 'Пакет нужен?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "No, I'm all set. Thanks!",
            react: { say: 'Awesome.', mood: 'smile' },
            coach: '«I\'m all set» — «мне больше ничего не нужно». Очень американское.', next: 'n6' },
          { tone: 'formal', text: 'That will not be necessary, thank you kindly.',
            react: { say: 'Okay! Very polite.', mood: 'laugh' },
            coach: 'Вежливо, но как у дворецкого. Проще: «No, I\'m good, thanks».', next: 'n6' },
          { tone: 'rude', text: 'Do I look like I need a bag?',
            react: { say: "Just asking! It's my job.", mood: 'frown' },
            coach: 'Риторический вопрос звучит как упрёк. Хватит «No, thanks».', next: 'n6' },
        ] },
      },
      n6: { who: 'luis', say: "Here's your receipt. Have a nice day!", ru: 'Вот чек. Хорошего дня!', end: true },
    },
  },

  /* ---------------- 10. Простуда ---------------- */
  {
    id: 'ep10-clinic', title: 'Простуда', place: 'Клиника без записи (urgent care) на соседней улице',
    intro: 'Утро. Голова тяжёлая, горло болит. Мэгги замечает это первой — и отправляет к врачу.',
    phrases: ["I don't feel well", "I think I'm coming down with something", 'I have a sore throat', 'Walk-in clinic', 'What seems to be the problem?', 'How long have you had these symptoms?', 'For about a week', 'Are you taking any medication?', "I'm allergic to penicillin", 'Does your insurance cover it?', "It's nothing serious", 'Get some rest', 'Drink plenty of fluids', 'Feel better soon'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'maggie', say: "Whoa, you don't look so good. Are you okay?", ru: 'Ого, выглядишь неважно. Ты в порядке?',
        reply: { type: 'open', prompt: 'Расскажи Мэгги, как себя чувствуешь.',
          meanings: [
            { id: 'sick', label: 'плохое самочувствие', keys: ['i do not feel well', 'coming down with something', 'under the weather', 'sore throat', 'headache', 'fever', 'sick', 'i feel terrible'],
              react: { say: "Oh no! There's a walk-in clinic around the corner. Go get checked out.", mood: 'warm' }, next: 'n2' },
            { id: 'fine', label: '«всё нормально»', keys: ['i am fine', 'i am okay', 'just tired', 'i am good'],
              react: { say: "Hmm, you sound sick. There's a walk-in clinic around the corner — humor me and go.", mood: 'confused' }, next: 'n2' },
          ],
          samples: ["I don't feel well. I think I'm coming down with something.", 'I have a sore throat and a headache.', "I'm feeling under the weather.", "I'm fine, just tired."],
          fallbackNext: 'n2' },
      },
      n2: {
        who: 'kim', say: "Hi, I'm Nurse Kim. What seems to be the problem?", ru: 'Здравствуйте, я медсестра Ким. Что вас беспокоит?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'I have a fever and I have a sore throat.',
            react: { say: "Okay, let's take a look.", mood: 'smile' },
            coach: 'Симптомы списком через «I have…» — так и говорят у врача.', next: 'n3' },
          { tone: 'formal', text: 'I am experiencing elevated body temperature and throat discomfort.',
            react: { say: 'Okay... so, a fever and a sore throat?', mood: 'confused' },
            coach: 'Так пишут в медкарте. Пациент говорит проще: «I have a fever».', next: 'n3' },
          { tone: 'rude', text: "Isn't it your job to figure that out?",
            react: { say: 'I need your symptoms to help you.', mood: 'frown' },
            coach: 'Болеть неприятно, но медсестра на твоей стороне. Опиши, что болит.', next: 'n2b' },
        ] },
      },
      n2b: { who: 'kim', say: "Let's start over. Fever? Sore throat? Cough?", ru: 'Давайте сначала. Температура? Горло? Кашель?', next: 'n3' },
      n3: {
        who: 'kim', say: 'How long have you had these symptoms?', ru: 'Как давно у вас эти симптомы?',
        reply: { type: 'open', prompt: 'Скажи, сколько дней ты болеешь.',
          meanings: [
            { id: 'time', label: 'срок', keys: ['for about', 'since', 'days', 'a week', 'yesterday', 'last night', 'this morning'],
              react: { say: 'Got it, thanks.', mood: 'neutral' }, next: 'n4' },
          ],
          samples: ['For about a week.', 'Since yesterday.', 'About three days.', 'It started last night.'],
          fallbackNext: 'n4' },
      },
      n4: {
        who: 'kim', say: 'Are you taking any medication? Any allergies?', ru: 'Принимаете какие-то лекарства? Есть аллергия?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "No medication, but I'm allergic to penicillin.",
            react: { say: "Good to know. I'll make a note.", mood: 'smile' },
            coach: 'Аллергию на лекарства называй всегда — это важнее всех остальных ответов.', next: 'n5' },
          { tone: 'formal', text: 'I do not consume pharmaceuticals. However, penicillin is contraindicated for me.',
            react: { say: '"Contraindicated" — you sound like a doctor! Noted.', mood: 'laugh' },
            coach: 'Медицинский термин понятен, но звучит книжно. Проще: «I\'m allergic to penicillin».', next: 'n5' },
          { tone: 'rude', text: 'No. Can we skip the questions?',
            react: { say: "These questions keep you safe. We're almost done.", mood: 'frown' },
            coach: 'Вопросы про лекарства и аллергию — про твою безопасность. Ответь, это займёт секунду.', next: 'n5' },
        ] },
      },
      n5: {
        who: 'kim', say: 'One more thing — does your insurance cover it? I need your card.', ru: 'И ещё — страховка это покрывает? Нужна ваша карточка.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "I think so. Here's my insurance card.",
            react: { say: "Perfect, you're covered.", mood: 'smile' },
            coach: 'В США спросят про страховку почти всегда. «Here\'s my insurance card» — главная фраза.', next: 'n6' },
          { tone: 'formal', text: 'My employer provides comprehensive medical coverage.',
            react: { say: "Great! Can I see the card?", mood: 'neutral' },
            coach: 'Верно, но длинно. Достаточно протянуть карточку: «Here\'s my insurance card».', next: 'n6' },
          { tone: 'rude', text: 'Ugh, money first, huh?',
            react: { say: "It's just how it works here, sorry.", mood: 'frown' },
            coach: 'Так устроена американская медицина, медсестра тут ни при чём.', next: 'n6' },
        ] },
      },
      n6: { who: 'kim', say: "It's just a cold. It's nothing serious. Get some rest, drink plenty of fluids, and feel better soon!", ru: 'Это просто простуда, ничего серьёзного. Отдыхайте, пейте больше жидкости — и поправляйтесь!', end: true },
    },
  },

  /* ---------------- 11. Вечеринка у Мэгги ---------------- */
  {
    id: 'ep11-party', title: 'Вечеринка у Мэгги', place: 'Бруклин, квартира, субботний вечер',
    intro: 'Мэгги позвала друзей. Половину гостей ты видишь впервые — время для настоящего small talk.',
    phrases: ['Come on in', 'Make yourself comfortable', 'Pleasure to meet you', 'How do you know each other?', 'Small world!', 'Honestly', 'Wanna hang out?', 'Count me in', 'Rain check?', 'It was a blast', "Let's do this again sometime"],
    start: 'n1',
    nodes: {
      n1: {
        who: 'maggie', say: 'Hey, come on in! Make yourself comfortable. Did you bring anything?', ru: 'Привет, заходи! Располагайся. Есть что-нибудь с собой?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'Yeah, I brought chips and salsa!',
            react: { say: "You're the best!", mood: 'laugh' },
            coach: 'На американскую вечеринку что-то приносят: снеки, напитки. Сказать об этом — просто и тепло.', next: 'n2' },
          { tone: 'formal', text: 'I have brought refreshments, as is customary.',
            react: { say: '"As is customary" — ha! Thank you!', mood: 'laugh' },
            coach: 'Звучит как этикет XIX века. Проще: «I brought snacks!»', next: 'n2' },
          { tone: 'rude', text: "No. You didn't say I had to.",
            react: { say: 'Ha, you totally don\'t have to! Just kidding around.', mood: 'confused' },
            coach: 'Оправдываться не нужно — Мэгги просто болтает. Лёгкий ответ: «Oh no, next time!»', next: 'n2' },
        ] },
      },
      n2: {
        who: 'sam', say: "Hi! I don't think we've met. I'm Sam.", ru: 'Привет! Кажется, мы не знакомы. Я Сэм.',
        reply: { type: 'open', prompt: 'Познакомься с Сэмом: поздоровайся и назови своё имя.',
          meanings: [
            { id: 'intro', label: 'знакомство', keys: ['nice to meet you', 'pleasure to meet you', 'my name is', 'call me', 'good to meet you'],
              react: { say: 'Nice to meet you too!', mood: 'smile' }, next: 'n3' },
          ],
          samples: ["Nice to meet you, Sam! I'm Alex.", 'Hi Sam, pleasure to meet you.', 'Hey! My name is Dana. I just moved here.', 'Good to meet you! Call me Kat.'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'sam', say: 'So, how do you know each other? You and Maggie?', ru: 'А вы с Мэгги откуда друг друга знаете?',
        reply: { type: 'open', prompt: 'Объясни, откуда ты знаешь Мэгги.',
          meanings: [
            { id: 'roommates', label: 'соседи по квартире', keys: ['roommate', 'roommates', 'live together', 'live with', 'moved in'],
              react: { say: 'Oh, nice! Lucky you — she makes great pancakes.', mood: 'laugh' }, next: 'n4' },
            { id: 'new', label: 'недавно знакомы', keys: ['just met', 'we met', 'last month'],
              react: { say: 'Small world! Welcome to the crew.', mood: 'warm' }, next: 'n4' },
          ],
          samples: ["We're roommates! I just moved in.", 'I live with Maggie.', 'We just met last month, actually. Small world!'],
          fallbackNext: 'n4' },
      },
      n4: {
        who: 'sam', say: 'So, what do you think of New York so far?', ru: 'Ну и как тебе Нью-Йорк?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Honestly? It's crazy, but I love it.",
            react: { say: 'Same! It grows on you.', mood: 'laugh' },
            coach: '«Honestly?» перед ответом — живая американская интонация. И честно, и тепло.', next: 'n5' },
          { tone: 'formal', text: 'I find the city to be highly stimulating.',
            react: { say: 'Highly stimulating! I\'m stealing that.', mood: 'laugh' },
            coach: 'Звучит как рецензия. В разговоре: «I love it» или «It\'s a lot, but it\'s fun».', next: 'n5' },
          { tone: 'rude', text: "It's dirty and way too expensive.",
            react: { say: 'Ha — fair.', mood: 'confused' },
            coach: 'Правда, но на вечеринке с местными лучше начать с хорошего, а минусы — с юмором.', next: 'n4b' },
        ] },
      },
      n4b: { who: 'sam', say: "But the pizza makes up for it, right?", ru: 'Зато пицца всё искупает, да?', next: 'n5' },
      n5: {
        who: 'sam', say: 'Hey, wanna hang out next weekend? A bunch of us are going to the beach.', ru: 'Слушай, хочешь потусить в следующие выходные? Мы компанией едем на пляж.',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "I'm in! Count me in.",
            react: { say: "Sweet! I'll add you to the group chat.", mood: 'laugh' },
            coach: '«Count me in» — «я в деле». Самый короткий способ согласиться.', next: 'n6' },
          { tone: 'natural', text: "Rain check? I'm working that weekend.",
            react: { say: 'No worries, next time!', mood: 'smile' },
            coach: '«Rain check?» — «давай в другой раз». Отказ, который оставляет дверь открытой.', next: 'n6' },
          { tone: 'formal', text: 'I would be delighted to join the excursion.',
            react: { say: '"Excursion" — ha! Love it. You\'re in!', mood: 'laugh' },
            coach: '«Excursion» — экскурсия для туристов. Друзьям: «I\'m in!»', next: 'n6' },
          { tone: 'rude', text: 'The beach? No thanks, sounds boring.',
            react: { say: 'Oh. Okay then.', mood: 'frown' },
            coach: 'Отказать можно, но «boring» обижает того, кто зовёт. Мягче: «Not really my thing, but thanks!»', next: 'n6' },
        ] },
      },
      n6: { who: 'maggie', say: "It was a blast. Let's do this again sometime!", ru: 'Было супер. Надо повторить!', end: true },
    },
  },

  /* ---------------- 12. Месяц в Нью-Йорке ---------------- */
  {
    id: 'ep12-month', title: 'Месяц в Нью-Йорке', place: 'Кофейня за углом, воскресное утро',
    intro: 'Ровно месяц с того дня в аэропорту. Та же кофейня, что и в первое утро, — только теперь тебя здесь знают.',
    phrases: ['Look who it is!', 'How have you been?', "Can't complain", 'Pretty good', "I've been keeping busy", 'Honestly', 'Home sweet home'],
    start: 'n1',
    nodes: {
      n1: {
        who: 'jess', say: 'Look who it is! The usual?', ru: 'Смотрите-ка, кто тут! Как обычно?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: 'You know it! A large latte, please.',
            react: { say: 'Coming right up!', mood: 'laugh' },
            coach: '«You know it!» — «а то!». Так отвечают, когда тебя уже знают.', next: 'n2' },
          { tone: 'formal', text: 'Yes, I would like my customary beverage, please.',
            react: { say: '"Customary beverage" — so fancy today!', mood: 'laugh' },
            coach: 'Звучит как заказ у дворецкого. «The usual, please!» — и всё.', next: 'n2' },
          { tone: 'rude', text: "Don't ask. Just make it.",
            react: { say: 'Ha. Somebody\'s not a morning person.', mood: 'frown' },
            coach: 'Даже сонным утром «please» решает всё. «The usual, please — I\'m half asleep!»', next: 'n1b' },
        ] },
      },
      n1b: { who: 'jess', say: "Extra shot, on the house. You look like you need it.", ru: 'Двойной эспрессо за счёт заведения. Тебе явно нужно.', next: 'n2' },
      n2: {
        who: 'tony', say: "Hey! How have you been? It's been a crazy month, huh?", ru: 'Привет! Как ты? Бешеный месяц вышел, да?',
        reply: { type: 'open', prompt: 'Ответь Тони, как прошёл этот месяц.',
          meanings: [
            { id: 'good', label: 'всё хорошо', keys: ['pretty good', 'can not complain', 'great', 'really good', 'good'],
              react: { say: 'Love to hear it!', mood: 'laugh' }, next: 'n3' },
            { id: 'busy', label: 'много дел', keys: ['keeping busy', 'busy', 'crazy', 'swamped'],
              react: { say: 'Ha, tell me about it.', mood: 'smile' }, next: 'n3' },
            { id: 'mixed', label: 'по-разному', keys: ['homesick', 'tired', 'miss home', 'up and down'],
              react: { say: "That's totally normal. It gets easier.", mood: 'warm' }, next: 'n3' },
          ],
          samples: ["Pretty good! Can't complain.", "I've been keeping busy, honestly.", 'A little homesick, but okay.', 'Crazy, but good!'],
          fallbackNext: 'n3' },
      },
      n3: {
        who: 'maggie', say: "Can you believe it's been a month already? What's been the hardest part?", ru: 'Представляешь, уже месяц прошёл! Что было сложнее всего?',
        reply: { type: 'open', prompt: 'Расскажи честно, что было труднее всего.',
          meanings: [
            { id: 'language', label: 'язык', keys: ['english', 'understand', 'accent', 'talk fast', 'speak fast', 'slang'],
              react: { say: "Honestly, half of New York talks too fast. Even me!", mood: 'laugh' }, next: 'n4' },
            { id: 'city', label: 'город', keys: ['subway', 'rent', 'expensive', 'the city', 'noise', 'weather'],
              react: { say: "Yeah, this city doesn't make it easy.", mood: 'warm' }, next: 'n4' },
            { id: 'people', label: 'близкие', keys: ['miss my family', 'my family', 'my friends', 'homesick', 'alone'],
              react: { say: "Aw. Well, you've got us now.", mood: 'warm' }, next: 'n4' },
          ],
          samples: ['Honestly? Understanding people when they talk fast.', 'The subway, for sure.', 'I miss my family sometimes.', 'Everything is so expensive!'],
          fallbackNext: 'n4' },
      },
      n4: {
        who: 'tony', say: 'So... does New York feel like home yet?', ru: 'Ну что… Нью-Йорк уже чувствуется домом?',
        reply: { type: 'choice', options: [
          { tone: 'natural', text: "Yeah. It's starting to feel like home.",
            react: { say: "That's what I wanted to hear!", mood: 'laugh' },
            coach: '«It\'s starting to feel like home» — «начинает ощущаться домом». Простая и тёплая фраза.', next: 'n5' },
          { tone: 'formal', text: 'I would say I have successfully integrated.',
            react: { say: '"Successfully integrated" — like a software update!', mood: 'laugh' },
            coach: 'Звучит как отчёт об интеграции систем. Про чувства говорят проще.', next: 'n5' },
          { tone: 'rude', text: 'Ask me again when the rent is due.',
            react: { say: 'Ha! Fair enough.', mood: 'confused' },
            coach: 'Шутка про аренду поймут все ньюйоркцы — но в такой момент она немного колкая.', next: 'n4b' },
        ] },
      },
      n4b: { who: 'tony', say: "But seriously — we're really glad you're here.", ru: 'А если серьёзно — мы правда рады, что ты здесь.', next: 'n5' },
      n5: { who: 'maggie', say: 'To your first month! Home sweet home.', ru: 'За твой первый месяц! Дом, милый дом.', end: true },
    },
  },
];

if (typeof window !== 'undefined') { window.SCENE_CAST = SCENE_CAST; window.SCENE_EPISODES = SCENE_EPISODES; }
if (typeof globalThis !== 'undefined') { globalThis.SCENE_CAST = SCENE_CAST; globalThis.SCENE_EPISODES = SCENE_EPISODES; }
